#lang racket
(cond
 (#\፲
  (let ((e2 (let ((a1 #\宱)) (integer? #f))))
    (char? (cond (e2 #\U000E7AA4) (else #t)))))
 (#t
  (if #\䋜
    (cond
     (#\U000E766D #f)
     (#\퐅 #t)
     (#f (if #f #f (if #t #f #f)))
     (#t (if -3 -1 -3))
     ((if #f #t (if -2 -5 #t)) (add1 #\쓏))
     (#\U0010851D #\U000830DE)
     (#\쑊 #\U0009F10A)
     (#\𢋶 -2)
     ((if 0 (if #f #t #t) (add1 #f)) (cond (#t #\Κ) (else (sub1 #t))))
     (#t #\け)
     ((integer? #f) (if #t (boolean? #f) (cond (#f #\뽌) (else #\U00104F6C))))
     ((cond (2 (if -1 #t #\U000FE11E)) (else (if #t #\佴 #f))) #t)
     (#\U000A43DD #\䨯)
     (-4 (char? #t))
     (-2 #\瞚)
     (3
      (cond
       ((add1 #t) #\U000BA1CA)
       (#\uF71D (abs #\U00050B41))
       (#t (cond (16 #f) (#\U000ADE1A #\ᆙ) (else #f)))
       (else #f)))
     ((add1 -5) (if #\U000DAFD9 (- 4) #\U00033A1A))
     (#f #t)
     ((integer->char (cond (else -2))) #f)
     (#\U00054767 4)
     ((cond ((char->integer #\뚄) 3) (#t #t) ((integer? #f) #t) (else -1)) #\눩)
     (else #t))
    (if #t (char? #f) (cond (#f 4) (else #\柾)))))
 ((sub1
   (cond
    ((cond
      (-3 #\U000C4E40)
      (#f #f)
      (#\𪔩 #f)
      ((if #\Ꝋ
         (if (if (zero? #\U000BD993) #f #\U000AFDC2)
           (integer->char (cond (else 3)))
           (cond ((sub1 #t) #\U000C0839) ((if #f #t #t) #f) (else #t)))
         #f)
       #t)
      (#\ᵨ -1)
      (4 #\筩)
      (else #f))
     #f)
    (#t #t)
    ((- (integer->char #f)) #\完)
    ((if 3 #\𢭗 2) (let ((d1 #\㿀)) #\U0007B7DC))
    ((cond
      (#\⌶ #f)
      (#\U000B4D03 #f)
      (#\剛
       (cond
        (else
         (cond
          ((char->integer 4) #t)
          (#f #\ᖤ)
          ((cond (#f #f) (#\U00063787 -2) (else #\U000D3DA6))
           (cond
            (#t #t)
            ((sub1 #t) #f)
            (#\ꚑ #t)
            ((cond (#\uA95B #f) (#t #t) (#\u0FDF 3) (else #\濷)) #t)
            (#f #f)
            (-1 2)
            (1 8)
            ((zero? #\蘐) -16)
            ((if #\U000CA5A7 #t #f) 1)
            (#\旝 #\U0006B5BA)
            (-1 #f)
            (#f (add1 #f))
            ((cond (#t #\U000714E4) (else 5)) #\U00107CDE)
            (else 1)))
          (#f
           (cond
            ((if 2 #f 5) -2)
            (#f (abs #\㚬))
            (2 #f)
            ((if 0 #t -2) (char->integer #\U000BBA3B))
            ((- 10) (add1 #t))
            (#t (char->integer #f))
            (#f (if -1 #f 2))
            (2
             (cond
              (10 #\謰)
              (#\풡 #\U0006771C)
              (#\穸 #t)
              (#t #\U0003EADD)
              (2 #f)
              (else #f)))
            (-1 #t)
            (1 #f)
            (#t -2)
            (#f #f)
            ((char? 4) #f)
            ((- #\桖) 3)
            ((char? #\U0010F770) #t)
            ((cond (#f #\⦣) (-2 #\돏) (#f #\园) (#f #t) (else 2)) #t)
            (#t (if -1 #\U0003363B -7))
            (#t (if 2 #\龹 #f))
            ((if #f #t #f)
             (cond
              (#f #f)
              (#t #t)
              (-6 #f)
              (-12 #t)
              (#\U000A274E -3)
              (#f #\⏈)
              (else #\U0007DCD9)))
            (#\ᔔ #t)
            (#f (cond (1 #f) (-4 #f) (#f #\ㄬ) (#\U0002E19B #f) (else #f)))
            ((cond (else #\U00095D8F)) #f)
            ((if -3 1 #t)
             (cond
              (-3 #f)
              (1 #t)
              (#t 4)
              (-1 0)
              (#t #\U00103346)
              (-2 0)
              (#\U0009ED8B #t)
              (#\U0006EC68 #f)
              (-1 #\U000904C9)
              (1 #f)
              (#f #f)
              (#\U000FE9C0 2)
              (else #t)))
            ((char? 4) #f)
            ((char->integer #\U000C51BC) #f)
            (#t #\U000428F1)
            ((if #t #f #\𑖦) -4)
            ((if #t #t #f) -1)
            (#f (cond (#f #\U0010A64C) (else #t)))
            (#t (if #f #\U00051D2B 2))
            ((if #t #f #t) #t)
            (#\U000F1D93 #t)
            (#f (if #t #f #f))
            (-9 #t)
            (else #t)))
          (#t
           (if #t (cond (1 2) (#t #t) (5 #\ோ) (#\弯 #\U00084BBF) (else #t)) #f))
          (#f #f)
          (#\댚 4)
          ((if #\㬱 (abs #\U000CB01D) #f) #t)
          (else (sub1 -2))))))
      (else (char? #\U00101C2E)))
     0)
    (#t #t)
    (3 (if #t -3 (if #t #f -2)))
    (else #t)))
  #f)
 ((let ((a0 #\ヿ)) #\U0009A48D)
  (cond
   (#\ʗ -2)
   (#f #\흽)
   (#f
    (cond
     (#t #\혦)
     (1 -3)
     ((abs -1) #\U000762DF)
     (#\諕 #\ꅋ)
     (1 -2)
     ((cond
       (#t #t)
       (#f #t)
       (#\U0009227E #t)
       (-2 4)
       (#f #t)
       (-2 #\U000D17CE)
       (#t
        (if #f
          #t
          (if 1 (cond (#f #f) (#\U0003D82E -256) (else #\펺)) (integer? -3))))
       (0 #f)
       ((cond
         ((if #f 5 #f) #t)
         (5 8)
         ((cond
           ((if (add1 -2) #\U0004E062 #t) (if -34 #f (if 1 -1 #t)))
           ((if (zero? #\恿) (if -17 #t #t) #\䝤) (if #t #t (cond (else #\㖞))))
           ((zero? #\뎇) (zero? #f))
           (#\U00105C19 #\饎)
           (#f (cond (else (char->integer #f))))
           (#f #t)
           (-4 (char? #\咽))
           ((if (if #f #\縡 -3) #t (char? #\U00066F23)) 1)
           ((char? #f) #f)
           ((if #f #f (if #\U0004FC14 1 12)) #f)
           (#f
            (cond
             ((- -4) (if #f 2 3))
             (-34 (if #f #t #\辞))
             ((integer->char -1) (cond (6 3) (else #t)))
             ((cond (#\˳ -3) (else 16)) #\U0004A2B5)
             (else 1)))
           (else
            (cond
             (#\锪 #t)
             (#f (cond (#t 11) (else #t)))
             (#\U0001E3E1 2)
             (#t (if #t #t 3))
             (#\꾗 1)
             ((cond (-4 #t) (else #f)) (add1 #\葐))
             (#f (if #\U000AB9A2 -2 #f))
             ((if #t #t -3) #\펙)
             ((if #f #\U0010C12E #f) #t)
             ((zero? #t) (cond (2 #f) (1 #\꿅) (#f #f) (else #f)))
             ((if #\巕 6 #\U000A10B4) (- #f))
             (#f (add1 -5))
             (else #f))))
          #t)
         (else (integer? #f)))
        (cond
         (#t
          (cond
           ((cond
             ((if #t #t 4)
              (cond
               (#f #f)
               (-1 #t)
               (#f #\U0008FE8A)
               (#f #t)
               (-3 1)
               (else #\숪)))
             ((cond (#t -6) (else #t)) #t)
             ((boolean? #t) 2)
             ((if #\劓 #f #f) (if #\U00102EE2 #\U000B6CF6 #t))
             ((if 2 #\U0007DA19 2) #t)
             ((cond (else 2)) (if -1 #t #t))
             ((sub1 #f) -1)
             (#t #t)
             ((zero? #f) -9)
             (1 #t)
             (else #f))
            #f)
           (else #t)))
         (#\촐 (if 4 #f #t))
         ((if #f (zero? (zero? -8)) #f)
          (cond
           ((cond
             (#t (- #f))
             ((if #t #\컼 8) (char? 0))
             (#t #\꧇)
             (2 (cond (else #\㽛)))
             (else (zero? #\헵)))
            (cond
             ((if #\ᵰ #t #f) -4)
             ((cond
               (#f #t)
               (#\姽 #\㲦)
               (2 4)
               (5 #f)
               (#f #f)
               (#\U000FF77B 1)
               (#t #\U00034B56)
               (#\U000A87D1 -8)
               (#\䂮 #f)
               (#\U000B0F0E 0)
               (#f #t)
               (#f 2)
               (#t #t)
               (#t #f)
               (1 1)
               (#f #t)
               (#\鮀 #f)
               (#f #t)
               (-4 -8)
               (-1 -1)
               (#\埇 3)
               (-2 -3)
               (#f #t)
               (#f -3)
               (#f #f)
               (#f -1)
               (#\㝒 #f)
               (#\U000B6450 #\U0005F413)
               (#f #\臉)
               (else #\ν))
              #t)
             ((add1 #\滆) #f)
             (-6 #f)
             ((cond
               (#\U0005E37E 2)
               (#\䱽 #f)
               (#f #t)
               (#\힓 #\U0004DECB)
               (#t #f)
               (#f #\渊)
               (#f #f)
               (#\U0010FD8E -4)
               (#\U0006DCE4 4)
               (1 1)
               (#t #f)
               (#t #t)
               (else #t))
              #\Ȿ)
             (#f #\ꁐ)
             (else #\턘)))
           ((cond
             (8 (abs #\U000412EF))
             (#\딋 (cond (#\U0008FBB5 #t) (#f #f) (else #\昹)))
             ((if #f #t #\U000BD85F) #\U000AF33F)
             (#f (add1 #\U00077791))
             (#f #f)
             (else (abs 1)))
            (cond
             (#t #t)
             ((char->integer #\鯦) -6)
             (#\Ꮁ (if #f #\㊋ #f))
             ((sub1 4) (cond (else 5)))
             (else #\u2B96)))
           (else #t)))
         (#\넁 130)
         ((cond (else -1)) #\U000FF6E9)
         (else
          (cond
           ((cond
             (1
              (cond
               (-1 #f)
               (#\뷵 -8)
               (6 #\는)
               (-8 #f)
               (#\䢪 #\U00090D6F)
               (-8 -18)
               (#f #\鞲)
               (#\U000F3010 #f)
               (#t #\U0010A4A5)
               (3 #f)
               (else #t)))
             (2 #\U000D6D42)
             (#t #\U0002E798)
             (else (if 1 #t 0)))
            #\U00082695)
           (-3 #f)
           (else (if #t 1 (zero? -2)))))))
       (#f #t)
       (#t #f)
       (#\벰 #t)
       (#\髨 3)
       (else
        (cond
         ((char?
           (char?
            (cond
             (#\U0008EB0E #f)
             (10 -1)
             (#f #\➬)
             (#t #f)
             (#\U000B130E 3)
             (#f #t)
             (else #f))))
          (add1 (abs (if 1 #t #f))))
         (else #t))))
      (if (if -3
            (cond
             (#t #\U000BC69D)
             (#\꿌 (char? #\瘰))
             ((if -8 #f #t) 8)
             (#f #f)
             ((if -1 #\͙ #\쉏) #\ᩘ)
             (#t #t)
             ((sub1 #f) #\U00102246)
             (else (- #\U0005B650)))
            #t)
        #f
        (cond ((if #t -18 #t) #t) (else #t))))
     (#t #\U0004B97B)
     ((if 1 #\뻋 #t) (if #f #t -1))
     (#t (cond (else #t)))
     (#\㱽 (if -2 -33 #t))
     (else (let ((a1 -3)) #f))))
   (#\U00101B74
    (if (if #\皚
          (cond
           ((sub1 (cond ((if 1 2 #\U000B76C9) #t) (1 2) (else (if #t #t #\䢾))))
            (cond (#t #t) (#t #t) (else #f)))
           ((- #f) 1)
           ((char? #\憽) -5)
           (#t #f)
           ((cond
             ((cond (else 0)) #t)
             ((if #t #t -3) #f)
             (#t 1)
             ((cond (else #\ꀼ)) #\𡶵)
             (-4 -3)
             (1 #t)
             ((cond
               ((cond (-3 2) (-3 #f) (#f 5) (#t -2) (else #f)) #t)
               ((if 2 #f #f) (if 1 #t #f))
               (#f (if #f #f #\U0001B046))
               (else #t))
              #t)
             (#\U00018FAC #t)
             (#t #\ꔕ)
             (#\u0CDC (if #t (boolean? #\U000C6317) (abs #f)))
             (#f #f)
             (else #t))
            #f)
           ((if -16
              (integer->char (cond (#t #f) (#f -3) (#t #\ត) (else -2)))
              5)
            (cond (else (cond (-1 #\U000F2554) (else #f)))))
           (-65
            (integer?
             (cond
              ((if #\៓ #f #t) (zero? #f))
              ((integer->char -5) (sub1 #t))
              (else (if #\U00045F8B #t #t)))))
           ((integer? 8) #f)
           (#t 1)
           (#\㿹 (char? 4))
           (1 -3)
           ((if 7 8 #f) (char? #\햟))
           (#\篬 #f)
           (else #f))
          #\淌)
      #\U000D9ECC
      #\U0006BA7A))
   (#\U000A6825 #t)
   ((cond
     ((let ((u0 256)) #f) #f)
     ((let ((s1 -1)) -5) #\Ĉ)
     ((if (cond
           (#\U000C6E82 (sub1 (integer->char 2)))
           (#\掆 #\崨)
           (#\U0002DAF4 (integer->char (if #\U000D64D4 #t #t)))
           (#t #t)
           ((add1 (char->integer #t)) #t)
           (16 #f)
           (else (integer? (if #\U000FC869 #t #\瓺))))
        (cond
         ((cond
           ((cond (else #f)) (if #t 3 -7))
           (#f (if #f #t #\uF1B4))
           ((if #\U000F5EF3 #\ᎎ #f) (cond (#t #f) (#t #f) (-4 #f) (else #\跌)))
           (1 #t)
           (else
            (cond
             (#\聺 #f)
             (#\컪 #\謐)
             (2 #t)
             (#\탐 #t)
             (-1 #t)
             (-8 5)
             (#\U000DE033 #\䀶)
             (#t -4)
             (-3 #f)
             (#t #f)
             (#t #\㕥)
             (#\U000C8651 #\郷)
             (else #f))))
          5)
         (else #t))
        -1)
      #f)
     (#\U00068267 3)
     (else (cond (else -2))))
    #f)
   (-9 #\U000C55F7)
   (else #f)))
 ((char->integer
   (if (if #f
         #f
         (if (cond
              (#t #f)
              (#\ꈈ (cond (2 #f) (#f #t) (else 1)))
              ((char? #t) (- #\թ))
              (else
               (cond
                (#\㹐 (if #t #f #\U000BE428))
                (-6 #\U000556E7)
                ((if #t 6 #\U0008B6D1) 0)
                (#f (cond (#f #t) (#t #t) (else 2)))
                (#t 67)
                (else #\ퟙ))))
           (abs #\U000FB277)
           #f))
     (let ((y0 -9)) #\㣻)
     (let ((q2 #t)) #\巯)))
  #t)
 (else
  (cond
   ((if (if #t #f #f) (boolean? #t) #\U000D497C) #t)
   ((let ((m2 (cond (else #t)))) #t) (if (if #t #\꩘ #t) (integer? #t) #t))
   (-1 #f)
   ((let ((p1 1)) 2) (if #\U000BB38B 2 #\ꃀ))
   ((cond (else #\U0003615D)) -3)
   (2 -3)
   ((sub1 #f) #\U0005AD96)
   ((if (let ((b2 #f)) #\U0009233A) (let ((s2 1)) #\u9FED) #\ଭ)
    (let ((v1 #f))
      (cond
       (v1 -4)
       (#t #f)
       (#t #f)
       (v1 #t)
       (#f #t)
       (#t v1)
       (v1 #t)
       (#t v1)
       (#t #t)
       (#f #t)
       (else v1))))
   (-2 (let ((r2 #t)) #\U00069B88))
   (else #\⡁))))
