#lang racket
(cond
 ((cond
   (#t #t)
   (2 #f)
   (#\℥ (if 2 (if #f 8 #t) -1))
   (#f (if #f (if #\U00033DA3 #f #\U000129A4) (- #f)))
   ((let ((e1
           (sub1
            (cond
             (-2 #\ڮ)
             (#t #t)
             (#f (if #f (char->integer -1) #\U0004A191))
             ((cond
               ((- (if #t #t #f)) (if (abs 6) 2 (add1 #\U0008A837)))
               ((- (cond (else #t))) (- #\谖))
               ((if -3 (if #f #f #f) (cond (-2 #\ᑱ) (else #\U0007584E))) -5)
               (#\鶪 (if #t (cond (else #t)) 1))
               ((cond
                 ((add1 #t)
                  (cond
                   (#f #t)
                   (3 #f)
                   (#f #f)
                   (#\鉰 #f)
                   (#\廽 #\U000FE043)
                   (else #t)))
                 (else (if #f -1 #\U000CD929)))
                -3)
               (#f #f)
               ((if #f (abs #t) #\U000A15DF)
                (cond
                 ((cond
                   (#\菀 -9)
                   (#t #t)
                   (#t #t)
                   (#t #\U0007DB03)
                   (4 16)
                   (else #f))
                  #f)
                 (#f #f)
                 (else 1)))
               (#\U00067FFB
                (cond
                 ((cond
                   (#t -1)
                   (#\U0008250F -3)
                   (#f #\堪)
                   (#\쐐 #t)
                   (#\䊊 #f)
                   (-2 #t)
                   (#t #f)
                   (else #\꾫))
                  #f)
                 (else (integer? #t))))
               (-4 #f)
               ((zero? #f) #\U0005ABDD)
               (#f (char->integer #t))
               (#t 5)
               (else #\U000467D5))
              #f)
             (#t #\书)
             ((cond
               ((boolean? #t) (cond (#\ꆧ #t) (else #f)))
               (#\U000FD2D5 #\U0008AAB3)
               (else 1))
              #\뵷)
             (else #t)))))
      (let ((c1 #t)) c1))
    (cond (else 260)))
   (#f #f)
   (#t -2)
   (#t (let ((k0 (cond (#t #f) (#\糛 #f) (else -3)))) (abs k0)))
   (else (integer? #t)))
  #\U000C5307)
 ((- #\U0009D7A1) (integer? #\䐴))
 (2 #\U000F7930)
 (#f (let ((f2 (if 3 1 (cond (#t #t) (else #t))))) #\鋑))
 (#\噾 5)
 (#\U00052A2F #t)
 ((let ((p1 #f)) #t) #\ڟ)
 (-5 #\ᝑ)
 (#f (if (cond (else (let ((i2 #\痮)) #\鷘))) #f -4))
 ((abs #\U0004E846) 17)
 (#\U000CAFDE
  (cond
   ((cond
     (#t #\Ỳ)
     ((char? #f) #t)
     ((char? -1) #\滏)
     ((let ((r2 #f)) #f)
      (cond
       (#t #f)
       (#\듻
        (cond
         ((cond
           ((cond
             ((cond
               (1 -32)
               (-3 -2)
               (-4 -2)
               (#\U00046132 -1)
               (#\ᢷ #f)
               (#\U000DB1E1 #t)
               (else #\؉))
              (if #f #f -1))
             (0 (sub1 #t))
             (#f (cond (1 #f) (#f #\ቊ) (#f 2) (else #f)))
             (#\⸋ (cond (#f #t) (#f #\U0005A306) (-1 #t) (3 #\县) (else #t)))
             (-2
              (cond
               (#\쌙 #f)
               (#f #\U000D3350)
               (0 #\쨀)
               (#t -2)
               (#f -2)
               (#t -1)
               (else #\U00095474)))
             (else (if 1 #t -2)))
            (abs (if -2 #f #t)))
           (2 #\섅)
           (else
            (cond
             (-2 (if #\溍 #t #\킒))
             (-5 #t)
             (#\Ꞑ (if 1 #\U00079310 #\섖))
             (else (cond (#\U0009984A #t) (else #\⭖))))))
          (if (sub1 #f) #\U000BD571 8))
         (else (char->integer #f))))
       (-2048 #f)
       (#\U000719B4 #f)
       (#f #f)
       (#t #t)
       (#\U00053A2B 3)
       (else #t)))
     (#f (cond (#\氼 #t) (#f #\甑) (#f #t) (2 #f) (else #f)))
     (#\耗 #t)
     (#t (- #f))
     ((let ((o0 1)) o0) (let ((v0 #t)) #f))
     (-1 (if #t #\U000DCBEF -2))
     ((char? #\놖) #\U000EF9EA)
     ((integer->char #\븴) 64)
     (else (cond (else 4))))
    #f)
   (-8 #f)
   (#f 5)
   (#f #t)
   (else 1)))
 (#\U0005E7B4 4)
 (1 #\哊)
 (#t 3)
 (-1 (integer? #t))
 ((integer? (abs (zero? #f))) #t)
 (#\U00048688
  (cond
   (#\弅 -2)
   ((if #\篿 (- (if #\ᒤ (if #t #f #t) (integer->char #\U00106581))) #\阯)
    (if #t
      (cond (#f #f) (#\U000AE168 (if 4 #\U0006E108 #t)) (else -3))
      (char? #t)))
   (#f (if (add1 #\U00060DA2) (sub1 -1) (let ((t1 #f)) #\U0010D457)))
   ((cond
     (#f
      (if #\U0004F8CC
        #f
        (cond
         (#t
          (cond
           (6 0)
           ((if -3 (cond (#t #f) (else -4)) -5)
            (cond ((abs #f) #\辴) (#\夵 (cond (else #t))) (else 4)))
           (#f (cond ((if 4 #t #t) #f) (else (if 2 1 #f))))
           (-2 #t)
           ((cond (else #t)) 2)
           (else (if #t #t #f))))
         (#\擾 (integer->char (integer->char #t)))
         (16 -4)
         ((cond
           ((if -16 1 #f) (add1 #\U000160D5))
           ((cond
             ((integer->char #f) (abs #\U000F8F87))
             (#f #\U000ED0B2)
             (#f (zero? 256))
             ((cond
               (4 #\ṻ)
               (#\U000E517D #f)
               (#t -32)
               (#f #f)
               (#\U00019CC5 #\敆)
               (#\U000AB976 #f)
               (#f #f)
               (#\묏 4)
               (else #\U000A7896))
              (if #f #\𐄞 #f))
             ((if #f #t #\뽣) #f)
             (#f (if #f #f #f))
             (else (char? #f)))
            #t)
           (0 #\覆)
           ((add1 (if #f #t #\仴)) (cond (#\U00083181 2) (else #f)))
           (#f #t)
           ((cond
             (#\U00015ABF #t)
             (#\껑 #\䝘)
             ((integer? -1) -1)
             (-1 (cond (#t 8) (#f #\𑆯) (else #\U000474A1)))
             ((if #\U0009F467 #t #\U00073758) #t)
             ((abs #f) (boolean? #f))
             ((cond (#f 1) (#f #f) (#\U000938F9 #f) (#f -5) (else -1))
              (if #\캠 -16 17))
             (#\ᛄ #t)
             ((if -4 #\邞 -1) #\쐪)
             ((if #f #\U00078CC2 -1) (- #f))
             ((cond
               (-2 #\U000B73AE)
               (#f #t)
               (#\闇 #f)
               (#\銪 #f)
               (#t -2)
               (#\颟 #t)
               (else #t))
              #t)
             (#t #f)
             ((if #t #f -1) -2)
             (1 #f)
             ((cond (#\U00041CA2 2) (7 #t) (-259 #f) (else #f)) #f)
             (else #\U000C43B7))
            #\U000AAB14)
           ((if (if #\U00051B5B #t #t) -3 1) 2)
           ((if 2 #\ⴌ -4)
            (if (cond (else #f)) (cond (#t #\傿) (else #\U000E592C)) #\湀))
           (#\U00081610 #\U000D444F)
           (-5 #\埿)
           (#t #\𧙓)
           (#\矈 (char? (cond (#t #\蟾) (#f #f) (else 2))))
           (#\U000354A6 #f)
           ((cond
             ((- -3) -3)
             (2 #\ᮉ)
             ((zero? 1) #t)
             ((- 8) (- #\U000D6819))
             ((cond (#f #f) (else #t)) (if 4 #\U000D6C65 #f))
             ((cond (#t #f) (#\㳿 #f) (else #\瞆)) 8)
             ((cond (#\U0009F5C4 0) (4 #\U00039670) (else 20)) 5)
             ((cond (#f #f) (#f #\㒢) (else #f)) #\U000DA770)
             (#\U00071BF2 #\U000C2A15)
             (2 #f)
             (6 (cond (#t #f) (#\U000978FC #f) (#t #t) (else -2)))
             (#\U0001CDE3
              (cond
               (2 #f)
               (#\U000F5CD8 1)
               (#f #\U00069782)
               (#\U0004FA1A #\U0009B0D1)
               (else #t)))
             (#\U0004D4DE #\U00016FC9)
             (#\ꨳ #t)
             ((- #\⥉) -2)
             (1 #\প)
             (#f -1)
             (else #f))
            (if #\U000BAD74 #f (if #\U000BE12D -1 -8)))
           (#\𤡦 (integer->char (if 3 #\⁕ #\U000D5BDB)))
           (#f (zero? #t))
           ((abs (add1 #\쿠)) (abs (cond (#f #t) (#t #t) (else #\U000897CE))))
           (#\弎
            (cond
             ((cond
               (#t #\U000E42C4)
               (#t #\U00010739)
               (#t #f)
               (3 #\𡯚)
               (else #\昨))
              (cond (else #t)))
             (else
              (cond
               (-3 #f)
               (#\螣 #\莁)
               (#t 34)
               (#f #f)
               (#\U000914A7 #f)
               (#t -2)
               (-1 #f)
               (#\蛫 #f)
               (#f #\댫)
               (#f #t)
               (else #t)))))
           (#\U000B3A7A
            (cond
             (#\误 (sub1 #\膀))
             ((if #f #f #t) #f)
             (#t #f)
             (else (if 3 #t #\U0008891F))))
           ((if #f
              (cond
               (0 #t)
               (5 #\U0007DD2B)
               (2 #t)
               (#f #\U000D3925)
               (#\㪌 #f)
               (#t #f)
               (#\駈 #f)
               (-1 #t)
               (-2 0)
               (#\U0001A832 #\魫)
               (else #t))
              #t)
            #f)
           (#\U000758F4 (if (integer->char #\U000D3CE2) (cond (else 1)) #t))
           (#f #t)
           (#f (if #f 2 #t))
           (#f
            (if (char? #\U0009CCA0)
              (if #\U00084B2A #f #f)
              (cond (-2 #t) (#f #f) (else #f))))
           (#f #t)
           (0 (cond (#f (cond (#\해 #f) (else #f))) (4 (if 2 #t #t)) (else -2)))
           ((cond
             (#t (if #t #t #t))
             (#t (cond (#t #\杶) (#f #\엨) (#\U00017B87 #f) (#f #f) (else #f)))
             (1 (cond (#f -3) (#f 17) (#t #\쁆) (else #t)))
             (else -2))
            0)
           (#t (integer->char (abs #\ຄ)))
           (#f #\㮟)
           ((if (if #\Ꙅ #f #f) #t (char? #f)) #f)
           (1 (if (cond (#t #\U0007C467) (else #t)) (if #f #\U0004837C #t) #t))
           (#\葇 (if #t #t #f))
           (else #f))
          (if #\U000E69A6 (- (if #t 6 #f)) #f))
         ((boolean? #\U00053A26)
          (cond
           ((cond (else (if #\U0006DE7B #t 8))) #f)
           (else (cond ((if #f 2 -3) -5) (else #\⍩)))))
         (#f (char? #f))
         (#t (zero? #f))
         (#f #f)
         ((cond (13 #\艍) (4 (integer? (char->integer #\U00042D0C))) (else 6))
          (if (cond (else 0)) #\आ #t))
         (#f
          (integer->char
           (cond
            (-2 #\얨)
            (#\官 1)
            (#\᱂ (boolean? #t))
            (-2 (abs #\衺))
            (#f (if 2 #f #f))
            (#f #f)
            (else (cond (#f #\U00010C9E) (else #f))))))
         ((if (boolean? #f) #\U000AA413 #t) #t)
         (#t #t)
         (else #f))))
     ((let ((y0 #\䘟)) y0) #f)
     (#t #t)
     ((let ((y0 #t)) y0) #\uAAC8)
     (-1 #\U000566F1)
     (#\虚 #\袖)
     (else
      (cond
       (#\U00032777 #f)
       (#\硬 #f)
       (else (char? (if (if -2 #\U00053D1B #f) (sub1 2) (if #\샴 #\喂 #t)))))))
    (integer->char 3))
   (-3 #t)
   (else
    (cond
     (-1 #t)
     (0 -2)
     ((cond
       (#f #f)
       (#t
        (if (boolean? -4)
          (if #t (integer->char #t) (char->integer (if #f -3 #\U000F4862)))
          (- #f)))
       ((integer? #t) (sub1 4))
       (#\᮲ #t)
       (else -1))
      (cond
       (else
        (cond
         (#\U000DB73B #\쾩)
         (2 #t)
         (#\U000A8C39
          (if #f
            (cond
             ((if 1 #f #f) #f)
             ((if #t 4 #t) #f)
             (-1 (if #\㽭 #t #t))
             (#\U000D6981 (- #f))
             (#f -2)
             (#f #t)
             (#\턢 (if #t #\U000A0E3A #f))
             (#f #t)
             ((sub1 -4) -6)
             ((abs #\U000D6E53) #\銧)
             (-1 #\퐌)
             ((if #f -2 3) #t)
             (#\U0008F626 #t)
             ((char? -1) #t)
             (-3 (if #\U000CE389 -1 #t))
             (else (if #\揊 #f 7)))
            #f))
         (#\U000F7BFA (char->integer #t))
         (else
          (if #t
            (if (cond
                 (-2 #f)
                 (#t 4)
                 (#\U000A7FD6 #\U00072C85)
                 (#\U0007CD4F #t)
                 (else -2))
              (add1 #f)
              #\㎫)
            (cond
             ((cond
               (#t #\眢)
               (6 1)
               (#f #\晈)
               (#f #f)
               (#f 66)
               (#\U000CBE00 #\ቼ)
               (#\㶧 #\͇)
               (#\뭌 #t)
               (#f #t)
               (3 -4)
               (else #t))
              (cond
               (#f #t)
               (#f #\U00017839)
               (#t -2)
               (#f #t)
               (#t #f)
               (#f #\詺)
               (#t 1)
               (#f #t)
               (#\გ #t)
               (else #\ꐻ)))
             (else -3))))))))
     (#\硣 #t)
     (#f #t)
     (#\섭 #t)
     (-3 (let ((o1 #t)) o1))
     (-1
      (cond
       (#t -1)
       (#t #t)
       (#t 2)
       (#t #\U000542AC)
       (#f #t)
       (#t
        (cond
         (#\ⴭ #t)
         ((add1
           (cond
            (#\狮 4)
            ((cond (#f #t) (else #f)) (if #\uF5F2 #f #t))
            (else #t)))
          #f)
         (#f #t)
         ((cond
           ((cond
             ((if #\U000154AC #t -4) #t)
             (#t #f)
             ((char->integer -1)
              (cond (#f #f) (#t #t) (#f 10) (#t -1) (else -3)))
             ((if #f #t #\拗) #\U000D9E57)
             (1 (if #t #f -1))
             ((if #f #\⸳ #\U00088F6C) #\U000EC10A)
             (#\̀ 1)
             (#t
              (cond
               (4 #\U0005D01B)
               (#f #f)
               (#\U000F79E7 #\즈)
               (1 1)
               (#f 5)
               (else -6)))
             (#t (if #f -3 #\U00065226))
             (#f (if #\⟐ #f #f))
             (-1 #\U00098870)
             (#f #\U000EE8B5)
             ((cond (#\U000FED42 #\𡶃) (#f #t) (1 256) (else #\U00062690)) -2)
             (#f
              (cond
               (#f 4)
               (#t #\U000FB3E8)
               (-16 #f)
               (#\ნ #t)
               (#f #f)
               (#\U0001868F #t)
               (#f -1)
               (#\U00083065 #t)
               (#\袔 #t)
               (#t #f)
               (#\臥 #f)
               (#\깩 #f)
               (#t #t)
               (#f #\⏹)
               (else 4)))
             (else #\ᴵ))
            -3)
           (#t (integer->char #f))
           ((if #f (add1 2) (cond (#f 1) (else #f))) #\삀)
           (#f #f)
           (-1 (if #\U00057A73 #f (cond (else #f))))
           ((if (cond (#\𨍠 #f) (#t #\䄨) (#f #f) (#t #f) (else #f))
              #f
              (char->integer #t))
            (cond (#\U000E15C3 #t) (else #t)))
           ((cond (else -5)) (cond (else #f)))
           (#f (if #f (abs #\佛) (zero? #\U00032D48)))
           (#\妛 (sub1 #\U000B9A63))
           ((if 128
              (cond (-4 #t) (else #f))
              (cond
               (-1 #f)
               (#f #t)
               (#t #f)
               (#\U0007B898 #t)
               (#t -2)
               (#\U0007110B 0)
               (#f #\Ὶ)
               (else 2)))
            #t)
           (else #t))
          3)
         (-1 #t)
         ((if #\㘱
            #t
            (abs (cond (#\U000F5612 #\绣) (-2 #\U0005C814) (-3 -3) (else #t))))
          #\包)
         (#t -3)
         ((cond (else #\U00094A11)) #f)
         ((if -5 #t (sub1 #f))
          (cond
           (else
            (if (if #f #t #\嗤)
              (if #\U00103149 #t -1)
              (cond (#t -2) (else #f))))))
         (else #\U000D391C)))
       (#f 2)
       (#t #\U000A2B0C)
       (1 #t)
       (#f (integer->char #f))
       (#f #\U000ED31C)
       (#t #t)
       (#t #f)
       (else #t)))
     ((cond
       (else
        (cond
         (#\U0005E99B #t)
         (#\U0010531C #f)
         (#f
          (abs
           (cond
            (-1 (cond (#\嬵 4) (#t #\uA97E) (#\ഇ #t) (else #t)))
            ((if 0 #\U000126A1 #f) #f)
            (#t 8)
            (else #f))))
         (#f #\U000F1F38)
         (else
          (cond
           (33 1)
           (5 (cond (else #\靗)))
           (#\U0004DB4E #\ᐔ)
           ((if (- #\Ȫ) (integer->char #\U0010273F) 1) #f)
           (#f #t)
           ((- #\ꖛ) #f)
           (else #t))))))
      1)
     (#t #\U000C1F36)
     ((cond
       (#f 2)
       (#f #t)
       (else (cond (else (if (abs (if -1 #t #f)) (boolean? #\U00089335) #f)))))
      (cond (else #t)))
     ((sub1 2) -2)
     ((cond
       (#\쪀 #t)
       (-6 #t)
       (#f #t)
       (#f #f)
       (#f #\Ĕ)
       (#t #t)
       (#\埫
        (-
         (integer->char
          (if (cond (#t #t) (#t #\u2BFD) (#\U00039D0F #\瓜) (#\໌ #t) (else #f))
            #f
            #f))))
       (else #f))
      (if #f (char? #f) #\U00056AFE))
     (#t
      (cond
       (#t 3)
       (3 #\U00066DF7)
       (#f #t)
       (#t #f)
       ((cond (else (if #\U000BABED #t (if #\様 0 #t)))) -4)
       (#\鐷 #f)
       (else
        (cond
         ((add1
           (char->integer
            (cond
             (#f -1)
             (-1 -16)
             (#f #t)
             (0 #\ꃝ)
             (#f #f)
             (#\䐔 #t)
             (#\U0009B349 #\U000C4E6D)
             (-256 #t)
             (#\u0EE9 #f)
             (2 #t)
             (#f -3)
             (5 #\U00062B06)
             (#f #f)
             (2 -256)
             (#f -3)
             (else #t))))
          #f)
         ((cond
           (#\𝀺
            (cond
             (#f 5)
             (#f
              (cond
               (#t #\뛝)
               (#t -6)
               (#\U0010E414 #f)
               (4 #\U000D217B)
               (#t #f)
               (#\U000C83E1 2)
               (#t #\牞)
               (#f 1)
               (#\U0005EE1E 4)
               (3 #t)
               (#t #t)
               (#\U000DF5A0 4)
               (-16 #\察)
               (#\ൌ #f)
               (#f 0)
               (#t #f)
               (#\U000C8DF3 7)
               (#t #f)
               (else #\⬹)))
             ((integer->char #f) (if #f -9 #\U0004925A))
             (else #\U0006110D)))
           ((boolean? (if -8 1 #f))
            (if (cond (#\U0005C4B6 #t) (#f #\U000A8C4E) (else #\U000404E9))
              (if #f #\U00013C72 #f)
              (cond
               (#t 2)
               (1 #\𦵧)
               (#\U000BF105 #f)
               (#\U0010DC1A #f)
               (#f #f)
               (-1 #f)
               (#\U0001C6AE #\꿀)
               (else #t))))
           ((if #t
              (cond (#f 9) (#t #\U0002E14A) (#f 3) (#f #t) (4 #f) (else -4))
              #\U0008B370)
            #t)
           (-6 #t)
           (#f (if -3 (if -4 #f #f) (if #f 2 #t)))
           (#f #t)
           (2
            (cond ((if #\䋍 -1 #t) #\U0008B16C) (#t (if #t #\屜 #t)) (else #f)))
           (#\샑 (integer? (integer? 2)))
           ((cond
             ((if #t #\䒂 #t)
              (cond (#t #f) (#\U000FB36B #t) (#\뇛 #\슓) (#t #t) (else #f)))
             ((cond
               (#t #f)
               (#t 2)
               (#\U0008E5B5 #\쭞)
               (#f 1)
               (#t #f)
               (#t -6)
               (#t #t)
               (-1 -5)
               (else #t))
              #t)
             ((cond
               (#f 34)
               (#t #t)
               (#\ힴ #\U00083807)
               (1 9)
               (#f #\U0004BE65)
               (else #t))
              (if #t -5 #\ꆈ))
             (else -1))
            (char? #\秐))
           (#f #f)
           ((sub1 #\U000A336E) #f)
           (#t #f)
           (#\U000AD40B #\蛱)
           (-4 -2)
           ((integer? #\狔) (cond (#f #\𧆛) (#f #\𫎳) (else #f)))
           (-4 0)
           (else (if (add1 #f) #\銉 (cond (#t -8) (#\U000A1E13 #f) (else #t)))))
          #t)
         (#\U000E6F10
          (add1 (if (cond (#f #\U000A3E36) (else -2)) 1 (cond (else #\룵)))))
         (-1 #f)
         ((char? #t) #f)
         (#f -2)
         ((char? #\ៈ) #\દ)
         ((zero? #t) (if (cond (else 4)) #t #t))
         (#f #\U000791E2)
         (#\瑘
          (if (cond (else #t))
            (cond
             ((if #\黩 -1 -4) (if #t #\U0003D4A4 #\U0009764A))
             ((abs #\U000B0B50) #t)
             ((add1 #\U000984B9) #t)
             (#\U000A53C6 17)
             (#f #t)
             (#f #f)
             ((boolean? #f) (if 1 #\ⴐ #t))
             ((abs #f) (cond (#f #t) (#\ഴ #f) (#f #t) (else #f)))
             (#f (if #f #\U000A7285 #t))
             (else (cond (else 4))))
            #\멳))
         (#\萬 -14)
         (#t (cond (#f (cond ((add1 -1) -3) (else #t))) (else #t)))
         ((cond
           ((add1 -2) #\U00063519)
           (0 #f)
           (else (char->integer (integer->char #f))))
          (if (cond (else (if 2 #t #f)))
            32
            (if (cond (#\섰 #f) (3 #f) (else #\⣇))
              (if #t 0 #t)
              (cond
               (#t #f)
               (-4 -17)
               (2 7)
               (-1 #\櫲)
               (#\惺 #\U0009024B)
               (#\嫴 #f)
               (else #f)))))
         (#f (abs #f))
         (#f
          (zero?
           (if (cond (#t #f) (#t #t) (else #f)) (if #\U0005EE9B #t #t) -6)))
         (#\U0005DAB8 16)
         ((cond (-1 -1) (else (- (cond (#f #\喏) (#f #\聩) (#t #f) (else #f)))))
          (integer->char #t))
         (-3 (if (cond (else #f)) -7 (integer->char (cond (else 8)))))
         (else #f)))))
     (else (cond (#\띙 #f) (#f #t) (else #\U000B47DF)))))))
 (else #t))
