#lang racket
(let ((n1
       (if (add1 #t)
         (cond
          (#t -2)
          ((cond ((- #\U00049464) #f) (else #t))
           (if (cond
                (1 #\U0004C4E6)
                (#f -1)
                (32 -1)
                (#\U000BE54C #f)
                (#t #\U000C2C1A)
                (#f #t)
                (#\U00075322 #\鮉)
                (#f -16)
                (-2 #\U0003CA85)
                (#t #f)
                (2 #\ἀ)
                (#\檜 #t)
                (#\U00063B24 #\뇑)
                (#\젶 #t)
                (#f -1)
                (-4 #\U00048A3E)
                (#t #t)
                (#f #\㇆)
                (#\᜔ #t)
                (3 #f)
                (else 5))
             #\u0BE4
             (cond (else #\U0004045B))))
          (else #\U000B819A))
         3)))
  #f)
