#lang racket
(if (let ((n1
           (cond
            ((integer? 4) (if 3 #\膩 #t))
            ((let ((h0 #\碋)) #\U0003CE3A) (if #t #f #t))
            ((cond
              ((if (integer? #f) -2 -1) -4)
              ((integer->char #\U00041991) #\뮟)
              ((if #\U000FE34A (cond (#t #\癷) (else #t)) 3) #f)
              ((cond
                ((integer->char 1) (integer? (if -1 #\U0001AC34 #f)))
                (0 -3)
                (else
                 (cond
                  ((integer? #f) (boolean? -4))
                  (#\U0002FE9A (if 34 #f #t))
                  (else (cond (-8 #\曫) (else #\嬩))))))
               #t)
              (#\齫
               (if (cond
                    ((if #f #f #\U000B472D) (if -2 -1 -6))
                    ((cond
                      (#\돝 #\U00019197)
                      (#\U000763B5 #\鿁)
                      (#\직 #f)
                      (else #f))
                     #t)
                    ((char->integer #t) #\㢏)
                    ((sub1 #\U0007A3F0) (boolean? #f))
                    (#t (cond (#t #\U000D617D) (else #t)))
                    ((abs #\퇚) -3)
                    (else #f))
                 (cond
                  ((cond
                    (#t #t)
                    (#t -1)
                    (0 #t)
                    (#\䤬 #f)
                    (0 1)
                    (#f #t)
                    (#f #f)
                    (-2 #f)
                    (else #f))
                   #\U000CA32B)
                  ((if 1 2 #t) (cond (-1 #t) (#t #\U000AEC73) (else 1)))
                  ((cond
                    (#t #t)
                    (#t #\U00101621)
                    (#f -1)
                    (#\샵 #f)
                    (3 6)
                    (#t #t)
                    (#f #\U000D8EE7)
                    (#\睮 #f)
                    (else -8))
                   7)
                  (else (cond (else 1))))
                 -3))
              ((if (cond (else (integer? #t)))
                 (if (boolean? #f) 0 (cond (else #\钄)))
                 (cond (else #t)))
               (cond
                ((zero? #\騘) #f)
                (#t #\U00091242)
                ((- -32)
                 (cond
                  (0 #f)
                  (-2
                   (cond
                    (-2 #f)
                    (#f #t)
                    (#t 1)
                    (#t #f)
                    (#t #f)
                    (-5 -1)
                    (else #t)))
                  (#t #t)
                  (1
                   (cond
                    (-5 #\U000A098A)
                    (-4 #t)
                    (#\닮 #t)
                    (-5 #\ᗫ)
                    (else #\U0010FB40)))
                  (#t #t)
                  ((integer? -3) #f)
                  (#t #t)
                  ((cond
                    (#f #f)
                    (32 -1)
                    (#f #f)
                    (#f #f)
                    (33 #\㫋)
                    (#\䦵 #\揻)
                    (2 #f)
                    (else #f))
                   (cond (#t 2) (else #\쁢)))
                  (#\项 -8)
                  (#\U000E4453 -1)
                  (#\乷 #\慑)
                  (#\U000BA69E (zero? #f))
                  (0 #t)
                  ((abs 1) (cond (else #\플)))
                  (#\U00086470 (char->integer 2))
                  ((cond
                    (#f #\꿍)
                    (-2 #f)
                    (#f #t)
                    (#f #t)
                    (#f 1)
                    (3 3)
                    (#t #f)
                    (else #t))
                   #\䋝)
                  (#t #f)
                  (#\㱁 #t)
                  (#\盜 (char? 8))
                  (else 1)))
                (else #t)))
              (#t #t)
              (-3 2)
              (#\慢 #\鵾)
              (#t -1)
              ((if (cond
                    (#\믖 (cond (#\싊 #\ꬵ) (#f #\ቾ) (#t -3) (else #\U00059AEB)))
                    (else #t))
                 (abs #f)
                 #t)
               (integer?
                (cond
                 (#f (cond (#\늮 -5) (else #\㖇)))
                 ((if #\拁 #t #f) #f)
                 (#t #f)
                 (#f -2)
                 (#\U000480B7 #\U00047AD4)
                 (2 #t)
                 (#f #f)
                 (#f #\U000E4CA1)
                 ((if #\U000FAF78 #t #\U000DF2F1) #t)
                 ((cond (#t #t) (-8 -10) (else 0)) (if 1 #f -2))
                 ((cond (1 10) (#f #t) (8 #\䠯) (else #t))
                  (cond
                   (#\貧 1)
                   (-1 #t)
                   (#\u9FD3 1)
                   (#\U000DC57E #f)
                   (#f #f)
                   (#\𪇼 0)
                   (-1 #\꿪)
                   (#t #f)
                   (#f #t)
                   (#f #f)
                   (#f #t)
                   (#\鸈 #f)
                   (#t 3)
                   (#\U000C8C91 #f)
                   (#t #f)
                   (#\蒥 -4)
                   (-1 #t)
                   (#t #t)
                   (#\奠 #\铮)
                   (else #t)))
                 (#\U000A9B49 10)
                 (3 #\U000ABF2C)
                 ((char->integer #\냪) (- 1))
                 ((if #t 2 #\櫎) -1)
                 (#\U000A36DE #f)
                 (#f #f)
                 (#t (if #t #t #f))
                 (#t #\U0007331A)
                 (2 (add1 2))
                 (else (if 2 #f #\튆)))))
              (else
               (cond
                (1 #f)
                ((if (cond
                      (4 #\U0004995E)
                      (#t #t)
                      (#\ꊇ #f)
                      (#\ű #t)
                      (#f -2)
                      (#f #f)
                      (#t #t)
                      (else #f))
                   (if #t #t 0)
                   (sub1 #\U000D36CC))
                 #f)
                ((cond
                  ((cond (9 #f) (else #f)) #t)
                  (#t (if #t #t -33))
                  ((if #f #t #f) #\ๆ)
                  ((cond
                    (#f #\䦁)
                    (#\U000473C1 -1)
                    (#f #f)
                    (#\ဦ -6)
                    (else #\U000A311A))
                   (cond
                    (#t 4)
                    (#f #\⇹)
                    (#f #t)
                    (3 #\핐)
                    (2 #t)
                    (#\U00052B63 #f)
                    (else 19)))
                  (#t (integer->char 6))
                  ((integer? #t) #f)
                  (-1 (boolean? #f))
                  (#t #\U0010B407)
                  (#f #t)
                  (else #t))
                 (if #\U00067725 #\U00043F6B 4))
                ((if (cond (1 #f) (-4 #f) (else #\燼)) #t #\U000F4E7A) 1)
                (else #f))))
             #t)
            (else
             (cond
              (2
               (cond
                ((if #\U001038EB #\裰 (boolean? #\絝))
                 (if 2
                   (- #t)
                   (cond (#f -3) (-8 #f) (-2 #\U000FE995) (else #f))))
                (#t #f)
                (else #\쯖)))
              (#\㍠
               (if (cond (else (cond (#t -4) (else #f))))
                 (cond
                  ((cond
                    (-4 #\U0008A15A)
                    (#\U00057DFA 0)
                    (#t #\U000CF255)
                    (2 -1)
                    (#f #t)
                    (else #f))
                   (cond
                    (#t #f)
                    (#\邼 #\큳)
                    (#f #t)
                    (4 4)
                    (#t #f)
                    (#t -10)
                    (#f #f)
                    (else #t)))
                  (-12 2)
                  ((cond (else #\U0001FDEF)) (if #f #\㧒 #f))
                  (#t #t)
                  (#t #t)
                  (#f #\U000D538A)
                  (#t #t)
                  (#t #f)
                  (#t 2)
                  (-10 #t)
                  (1 (if #\U000D3260 #t #\U0010D50D))
                  ((if 1 #\U000E83FA #t) #\U000CF158)
                  (2 (if #f #\U00042BEC #f))
                  (#\ᠸ #t)
                  (#\䰓 (cond (#\U0005B946 #t) (6 #t) (else #t)))
                  (else (cond (#\꧍ #\U000A3188) (2 #f) (#\鵼 -3) (else 1))))
                 (cond
                  ((cond (#t -2) (else #\‷)) 3)
                  (else (integer->char #t)))))
              (else #f))))))
      (let ((c1 (cond (-4 #f) (-1 2) (#t #f) (else #t)))) (char->integer c1)))
  (cond
   (#t #f)
   (else (if (cond (else #\U0010240D)) #\U00090337 (let ((d2 #\ꂲ)) #f))))
  (let ((l2 #\鼎)) #\謫))
