#lang racket
(if #f
  3
  (cond
   (1 #\ힼ)
   (#t 3)
   ((if (let ((j2 #t)) j2) (integer->char #t) -2)
    (cond
     ((if #t (zero? #t) #t) (let ((m2 #f)) #\𨳾))
     ((let ((q2 #\U000AB369)) q2) #\U000B6E1A)
     ((if #f #\옶 #\餏) (char->integer #t))
     (#t #f)
     (else 133)))
   ((if #f (abs (cond (#\U00100074 #f) (else #\㠉))) #t) -1)
   (#f (if (let ((w1 -7)) #t) (cond (else #f)) (let ((x2 #t)) #f)))
   (#t #t)
   (#\U000AD5F4 #f)
   ((cond
     ((let ((r0 1)) r0) #t)
     (2 (let ((v0 (boolean? #f))) -2))
     (#f #\嵢)
     (#f #\U0009DBE7)
     ((let ((j0
             (if (if 16 (integer->char #t) #\U000351F4)
               (if (if (cond
                        (#t -4)
                        (5 #\U000A5E6E)
                        (1 #\U00015DF2)
                        (#t #\U00055CAD)
                        (#f #t)
                        (#f #t)
                        (#f #t)
                        (else #\ॳ))
                     #t
                     3)
                 #f
                 #t)
               #t)))
        #f)
      (if -1 #t #f))
     (#\U0007E3F4 (- 6))
     ((cond (#t #\U0005C7E4) (3 #f) (-1 #f) (-2 #\㔁) (else -2))
      (zero? #\uF44B))
     (else (cond (#t #\U00067652) (2 0) (-5 #t) (else #t))))
    (if #\옐
      (cond
       (-8 #t)
       (#\U000E1BBA -2)
       ((if #\㌿
          (char->integer (if (char->integer #\U000922DB) #f #\U000127B2))
          (cond
           (4 #f)
           ((cond
             ((- #\U00058A7B) #f)
             (#f #t)
             (#f (cond (else #t)))
             ((if #\빌 #f -2) #t)
             (-1 #f)
             (else (add1 #t)))
            #\U0002D983)
           ((cond
             ((cond
               (#\蹛 #t)
               (#\୨ #\U0006B195)
               (2 #\U0006B3DD)
               (#f #\ྂ)
               (#t #\U0003A7A9)
               (2 #f)
               (#\U000F15FE #t)
               (#t -5)
               (#t #\瑷)
               (else #\胲))
              (cond (#\U0006BAD0 #f) (#f 2) (else -2)))
             (#t (boolean? #t))
             ((cond (else -1)) #f)
             (#\U000D01DE (integer->char #t))
             (else #f))
            #\턷)
           (else (if (if #f #f #\U0002D047) #\U000E5575 #\U00063108))))
        2)
       ((cond
         (-2 #f)
         (else
          (cond
           (#t #\⳿)
           ((if 4 (char? #f) (if 1 #f #t))
            (if #t
              (cond
               (#\႞ #f)
               (#\U00014FE8 -2)
               (0 5)
               (-3 #\U000869AF)
               (#f #\U000D9DD6)
               (#\㿪 -5)
               (else #t))
              (integer? #f)))
           ((if #f (if #f #t #t) 2) (integer? #\ꈕ))
           ((if 4 (zero? #f) #f) (cond (else -2)))
           ((sub1 #f)
            (cond
             ((zero? #t) (zero? -10))
             (#t (cond (#t #f) (else #f)))
             (#\ဏ (integer->char #\ﮆ))
             (1 (if #t #\U0005C909 #\U00078CC9))
             (3 #f)
             (#f (if #\♘ #f #t))
             (#t #f)
             ((if 1 #f 2) (cond (3 16) (#f #f) (#f #\᱾) (else #f)))
             ((cond
               (3 #t)
               (#\U00072F73 #\u2D74)
               (#f #t)
               (#\U0009791B #f)
               (#\咜 #\緃)
               (else #t))
              2)
             (else (char->integer #t))))
           (#\U0001E14A
            (cond
             (6 #\U000A772D)
             (2 #t)
             (#t #\U000483E5)
             (#\몬 (cond (else #f)))
             (-1 (if #\㱿 #f #f))
             (#t #t)
             (else 2)))
           ((cond
             (#\U000CC7FF (if #\U000CC489 #t #\U000AA5FB))
             (#\U000F4CC4 -4)
             (else (if #f 0 #\U0007B007)))
            #t)
           (#t #f)
           ((integer->char (if #\쟔 -2 #f))
            (cond
             ((- -9) #\U00070722)
             ((cond (#\㭹 #t) (else #t)) (if #f -1 #\讓))
             (#f #\ਁ)
             (else
              (cond
               (#\U0009562B #\U0009BCA5)
               (#f #f)
               (-11 #f)
               (#f #t)
               (#f #\U00046BA1)
               (else #\敫)))))
           (#t 1)
           (-5 (if 5 (if #f #t #\U000B356E) (integer->char 0)))
           (3 #\㬺)
           (#f (abs (cond (#f #f) (#t 3) (-5 #\U000B2C68) (19 #\꽀) (else 2))))
           (#f #\⏳)
           (else #\䅳))))
        259)
       (#\厫 -4)
       (else 2))
      (if (cond (else (abs #f))) #t #f)))
   (#f (zero? #\亲))
   ((if #\뤺 1 8) (add1 0))
   ((zero? (if #f -6 0)) #t)
   (else #f)))
