#lang racket
(cond
 ((if #f
    (if (sub1 -12)
      -2
      (cond
       (#f #f)
       (#\𡃚 #\힙)
       (#t #f)
       (-1 #t)
       (#\똟 #t)
       (#\u08E2 -2)
       (-1 (abs #f))
       (#f #f)
       (else #\淼)))
    #t)
  (char->integer #t))
 (#t (abs #f))
 (#t
  (sub1
   (cond
    (33 #\U0010398B)
    (#\㪮
     (cond
      (#f #\U000FB8E4)
      (#f #\U000E7878)
      (#f #\U000AC86E)
      (#t
       (cond
        (-1
         (if (if (cond (else #t)) #\畸 (char->integer #t))
           #f
           (cond
            (-4 #\U0008CCC5)
            (#t #f)
            ((integer? #f) (cond (#f #\U000A59A9) (-2 #t) (#\띂 #t) (else #t)))
            (#\U0010B8B2 (cond (else -3)))
            ((sub1 #t) #f)
            ((cond (#\架 #\ꛉ) (else 2)) #t)
            ((char->integer #\U000F55BA)
             (cond (#\鐫 #t) (#t #t) (#t 2) (else #t)))
            (-17 7)
            (#\茊 #\ז)
            (#\U0008D8B7 (if #t #f #t))
            (-2 #f)
            ((sub1 #f) (sub1 #\ꎖ))
            ((if #t -4 #f) (cond (#\U000E4C13 #f) (else #t)))
            (#f
             (cond
              (#t -4)
              (#t #t)
              (#\U000D1B9E #\U000669DB)
              (#f -7)
              (else #\U0007731E)))
            ((if 2 #f #\U00034DFA) #t)
            ((cond (else -21)) #\⩍)
            ((boolean? 3) (cond (else #t)))
            (#t (if #f #f 34))
            (#t -2)
            (-1 -3)
            ((- #\U0007E85C) #t)
            ((cond (#f #\U000B3562) (0 4) (else 3)) #t)
            (else #\U000B66A5))))
        ((if (zero? #f) (if #\睱 #\謴 (if #\U000EDC9F #\廜 #t)) #\U00066146)
         (cond
          (#\U00094687 4)
          ((char? -1) #\ᇥ)
          ((if #t #t (char->integer #f)) -2)
          ((if (cond (#\藄 8) (else #t)) #f -4) -1)
          (#f #\U000197E5)
          (4 #\U000EDA92)
          (4
           (sub1
            (cond
             (#f #\U000A3F7B)
             (#\U000CC6B4 #\U00097DE3)
             (#f #\௸)
             (-2 #f)
             (-1 #\❥)
             (#t #f)
             (else #t))))
          ((char->integer (zero? 3)) 2)
          ((if #\U000DC397 (sub1 #t) #f) (if (if #t -1 2) (if #f #f #t) #f))
          (else #f)))
        (#\U00013EF3 -1)
        ((cond
          (32 #\줈)
          (#f #f)
          (#f (if #\쩁 2 #\룁))
          ((if (cond (#f #\⟗) (else #t)) #\ᬣ 4) 3)
          ((cond (#f #f) ((if #f #t -2) #t) (else #\쾟))
           (cond (5 (if #\얛 #\ޟ -2)) (2 #f) (else #\ꬤ)))
          (#f #\㕇)
          ((integer->char -1)
           (cond
            ((cond (#\镎 #f) (#t -134) (else #\ᘁ)) (if #\毊 #t #\虷))
            (3 #\렾)
            ((if #\U0005176C 1 -3) #t)
            (8 -2)
            (else (integer? #t))))
          (#t (if #\ⵣ (cond (#f -1) (-1 #t) (else #f)) (if 0 #f #f)))
          (#\瀌 #\U000D48BE)
          (else (if #\uFFFA (if #\魐 #t 1) 1)))
         #t)
        ((zero? #f) (sub1 (if (cond (else #\U000B2133)) (if #t #f #t) -6)))
        (#f #t)
        (#\U00058476 (boolean? (cond (else #t))))
        (else -4)))
      (#\U000C550B #t)
      (#\趫 0)
      (else #\U000DE5DA)))
    (#f
     (cond
      (#t #t)
      (#\U0002BE47 #\U000E7994)
      (#t #f)
      (6 (if #\U0008C568 4 #t))
      (#f
       (cond
        (#\陙
         (if 9
           (abs #f)
           (cond
            (#t
             (cond
              (#f #f)
              (#t #t)
              (#\ᔟ -2)
              (-8 4)
              (-2 #f)
              (#\u1717 #\傼)
              (#t #t)
              (else -1)))
            (#t -1)
            ((cond
              (#t #f)
              (#t 2)
              (#\玜 #\U0010D0B7)
              (-1 #f)
              (#\渍 #\U000D3D76)
              (#t #f)
              (#t #\U0001E344)
              (#t #f)
              (#t #t)
              (#t #f)
              (else #f))
             (if #f #\駻 #t))
            ((cond (#t #f) (#f #\U00068734) (#t 2) (else #\欯))
             (cond (else #f)))
            (4 #t)
            (#f (cond (0 2) (1 #t) (else -5)))
            ((cond (1 #t) (#f #t) (else #\蓘)) #t)
            (1 (zero? 0))
            ((cond
              (-6 #f)
              (#\㣰 #\俻)
              (4 #\ꗩ)
              (#\ᢵ #t)
              (#\U00068626 #t)
              (else #\先))
             (cond (#\䇖 #t) (#\匌 #\U00016626) (else #f)))
            ((if 2 #t #t) (cond (else #t)))
            (-2 -1)
            ((if #\U000DAD4B -3 #t) (abs -6))
            (#t #t)
            ((cond (else #f)) (char? 1))
            (#\U00056349 (sub1 -1))
            (else (if #f #\U000A908C 1)))))
        (#f -11)
        (#\ꏥ (- #\轔))
        (#\U00098745 129)
        (#\U0002D92F 1)
        ((if #f #t #t)
         (cond
          (4
           (cond
            ((boolean? #t) (cond (#\U000FCF83 #f) (else #\U000AEEA1)))
            (#t (cond (else #\ꁙ)))
            (#f #f)
            (#t (cond (#t #t) (5 #t) (else #\㉘)))
            (else (cond (else #t)))))
          ((boolean? #t) #t)
          (else
           (if (char->integer -2)
             (cond (-3 #t) (0 #t) (#f #\U000E125E) (else #f))
             (if #t -1 #t)))))
        ((zero? #\엷)
         (cond
          (#f (abs #\䠍))
          (#f (char? -1))
          (#\Ф
           (if #f
             #f
             (cond
              (#t #t)
              (#t #f)
              (0 #\ꏄ)
              (#t #t)
              (#\̿ #\租)
              (#\U00057398 #\ዝ)
              (#\땨 -1)
              (#\Ḙ #\ྒ)
              (else #f))))
          ((char->integer #\മ) (cond ((zero? #t) #t) (else #t)))
          (#f
           (cond
            ((char->integer #t) #f)
            ((cond
              (-4 #\U0010C658)
              (0 #t)
              (#t #t)
              (#f #f)
              (#\U0005033E #\U000AFF73)
              (else #t))
             #\u9FE0)
            (else #f)))
          ((cond (else #\U000A8636)) #f)
          (8 #f)
          (#\뽉 5)
          (else 1)))
        (#t 2)
        (#\U0003C723 (cond (#\𨆗 #\▣) (else #f)))
        (#t -128)
        (-5 (boolean? (boolean? (if -2 #t #\U0010FBB7))))
        ((if (- #t) -3 (integer->char (if #t #\ᶞ #t))) -4)
        (-2 -1)
        (-3 #f)
        ((cond
          (#f (boolean? (- #f)))
          ((zero? #\剟) #t)
          ((if -1 (if #f #\U000DE069 #\U000E8ED6) #\衺)
           (if (char? #\猀)
             (cond
              (#t #f)
              (#t -1)
              (#\ু 4)
              (#f -4)
              (#\𑁄 -9)
              (5 #t)
              (-19 #f)
              (#t #f)
              (else #f))
             (if #t #\U000B03B2 #t)))
          (#\U0004D05D -3)
          (5 #f)
          (#t (zero? #t))
          (#\熨 #f)
          (#\U00041DEF #t)
          (9 #t)
          (#t #f)
          (-1
           (if #\U000C9CC0
             (cond
              (#f #f)
              (#\U000E1DC6 #t)
              (#t #t)
              (#t #f)
              (#f -3)
              (8 #t)
              (else #t))
             4))
          (#t (boolean? #f))
          (-3 -2)
          (#\㮐 #f)
          (else #f))
         #\U0003FD2D)
        (0
         (cond
          (-2
           (if (cond
                (#t 4)
                (#f #\U0002E534)
                (#t #\U000BA848)
                (#\U000DFC12 #\咄)
                (else 5))
             (cond (#\흧 #\U0005B898) (#f #f) (5 #f) (else #t))
             (integer->char #f)))
          (#f
           (cond
            (#\扥 (if #f #t #\U000E3016))
            (2 #\U000CC66F)
            ((integer->char #t) (if -2 #\劈 #f))
            (-4 1)
            ((if #f 3 #\䂼) (- #\㴝))
            ((if #t #\䃣 #f) #\U000D3E30)
            (8 #t)
            (#t (if 3 #\욛 #f))
            (#f (- #f))
            (else (cond (else #t)))))
          ((- (if #\큌 #t 4)) #t)
          (-1 #\徛)
          (4 (if -2 (cond (#f #f) (else #\U00069D02)) #f))
          (#\翜 0)
          (else -2)))
        (#f #t)
        ((if -1 #\摉 #t) #\祊)
        ((char->integer (- #f)) #\U0001F91C)
        (else #\U00042F25)))
      (else #\ⱡ)))
    (#\㓴 (let ((g0 #f)) #t))
    (#t -1)
    (else (zero? #\U0004EE28)))))
 (#t (if 3 (if (char? -1) (add1 8) #t) #f))
 (#\瓄 #\ɣ)
 (#\㽡 (char? (let ((e1 -1)) (if -4 #t #\큯))))
 ((let ((b0
         (cond
          ((let ((g0 1)) g0) (if (abs #\迍) #\琐 #\u2DA7))
          (else (let ((p1 #f)) #t)))))
    -6)
  (if (if #f
        (if (if (integer->char -1) #t #f)
          (cond (else #f))
          (zero? (integer? #t)))
        (if #f 3 (integer? #t)))
    (sub1 (if -34 #t #t))
    #t))
 (else
  (cond
   (#t (zero? #f))
   (#f #\䠔)
   (#f (let ((v0 (abs #t))) #t))
   ((let ((z0 (integer->char #f))) 3) (zero? (let ((k1 #t)) -3)))
   ((integer? (cond (else -4))) #t)
   ((zero? 3) #f)
   ((if #f #f (abs #t)) (let ((o0 #\U000ABF19)) #f))
   (#\अ
    (let ((j0
           (if 1
             #\ᴨ
             (cond
              (#f 2)
              (2 #\U00049A5A)
              ((if 2
                 (if (integer->char #t) (if -32 #t #t) #\U0009C37C)
                 (cond
                  (#f (cond (else #\U00066014)))
                  (#t #t)
                  (#f (cond (4 #f) (else #\杽)))
                  (-13 #\砅)
                  (#f 4)
                  ((add1 -2)
                   (cond
                    (#f #t)
                    (#f #\拤)
                    (#t #t)
                    (#t #f)
                    (-1 #t)
                    (#\払 #t)
                    (else #t)))
                  ((cond
                    (#t -3)
                    (#t #f)
                    (#\U000F04C6 -1)
                    (#f #t)
                    (#t -18)
                    (#f #f)
                    (#t #\U000B36CB)
                    (#t #t)
                    (-2 1)
                    (else #\ꇮ))
                   2)
                  ((cond
                    (#f -2)
                    (#t 2)
                    (1 #f)
                    (#f #\U000FC95C)
                    (-1 #t)
                    (#\谚 #\돦)
                    (else 1))
                   #f)
                  (else (if #f #f 5))))
               (cond
                ((- #t)
                 (cond
                  (0
                   (cond
                    (#\艣 #t)
                    (#t #t)
                    (-3 16)
                    (#\ꗟ #t)
                    (#f -2)
                    (#t 5)
                    (#f #\犞)
                    (#t -17)
                    (else 4)))
                  (#t -2)
                  (#t #\U000CE2DF)
                  ((if #f #f -1) #\⇜)
                  (4 #\활)
                  (4 -3)
                  (else #t)))
                (-4 #f)
                ((abs (if #f #t #\ő)) #t)
                ((abs (char->integer #f))
                 (if #\U00032EB7 (char? #f) (cond (-2 #\쩵) (#t #t) (else 16))))
                ((cond
                  (#f #t)
                  (#t -2)
                  (6 #f)
                  ((if 6 #\U000D8B79 #f) -6)
                  (#t (integer->char #t))
                  ((- #t) (sub1 #\ᣖ))
                  (else (char->integer #f)))
                 #\U00055E93)
                ((cond
                  ((if #t #\U000985C8 #t) (cond (#t #f) (else -2)))
                  ((integer->char #\Ӆ) #f)
                  ((char? #\U000C45CD)
                   (cond
                    (#f #\㱰)
                    (#\U00073FE8 #\U000B2D5E)
                    (else #\U000868C0)))
                  (#t #f)
                  (2 (if #f #f 1))
                  (else #t))
                 (cond ((if #t #t #\虜) #t) (else #\輯)))
                (2 #f)
                ((cond
                  (#t
                   (cond
                    (-1 #\U000F8058)
                    (#\㋠ -65)
                    (#f #f)
                    (#\U0010321A #t)
                    (#\斖 #\ᔉ)
                    (#\㶣 #f)
                    (260 #t)
                    (#t #t)
                    (#t #\䓷)
                    (#\漣 #\U00048726)
                    (#\⪐ #t)
                    (else -1)))
                  (else #\U000FB06A))
                 #\U0007DE56)
                (else (- (if #f #\u0881 #t)))))
              ((if #\U00062C0A
                 (if #f (cond (#t #t) (-1 #\戇) (else #\U0008C6EF)) 0)
                 #\U000A7FF4)
               (if (if (cond (#t -1) (#t #t) (#f 2) (#f #f) (else 1))
                     (if -2 #\떃 #f)
                     (cond
                      (#f #\U000EA648)
                      (2 #t)
                      (#f #t)
                      (#f 18)
                      (#t #\콽)
                      (1 #\U000D8260)
                      (#f #f)
                      (#\陌 -64)
                      (#\U000E724E -5)
                      (else #f)))
                 (integer? (char? #f))
                 #t))
              (else #\ら)))))
      -3))
   ((let ((c1 #\䜭)) #\U00040490)
    (let ((y2
           (if #\U0001FB7D
             #f
             (cond
              ((cond
                (#\U00048302 #t)
                ((if (if #\𧅙 2 4) #\U00047EE8 #f) #\U000AA2CE)
                (#t #t)
                (#f
                 (cond
                  ((cond (else #t)) (if 3 #f #\U000A6BBF))
                  (1 (if #f #\U00044907 #t))
                  (else #\𢳿)))
                (#\镜 (if (sub1 #\U0008D2ED) #t #\U000D0E9B))
                ((if #t (zero? #f) #t)
                 (cond
                  ((if #f #\쓍 -4)
                   (cond
                    (#t #t)
                    (#f -1)
                    (#t #f)
                    (#f #t)
                    (5 #\绵)
                    (1 #f)
                    (4 #t)
                    (else #\两)))
                  ((cond
                    (#\⩀ #\藍)
                    (#f #\땋)
                    (1 19)
                    (4 #\쀙)
                    (-2 #f)
                    (1 -2)
                    (#f #t)
                    (4 #\uA7E5)
                    (else #f))
                   #\U00077860)
                  (else
                   (cond
                    (#f #t)
                    (#f -8)
                    (#\𩟈 #f)
                    (#t #f)
                    (-4 #\蠐)
                    (6 #f)
                    (#f #\副)
                    (#f #f)
                    (else 2)))))
                (-2 #t)
                (#f #t)
                (else #t))
               #f)
              ((if #t #\U0010AA50 #f) #\ꄳ)
              ((if (integer? (char? #t)) #f #\쾹) (zero? (abs #f)))
              (-3 -1)
              (3 #t)
              (else -9)))))
      #\楪))
   (else #\U000D0C04))))
