#lang racket
(if #f
  (if #t
    (zero? (integer->char #t))
    (cond
     (16 #\莁)
     ((cond (#\U00104096 1) (#t #t) (33 #f) (#f 3) (#t #t) (else #t)) 1)
     (#f (let ((h2 #\U000E4358)) #\Ꝙ))
     (#f #t)
     (#f (add1 #f))
     (#t #t)
     ((let ((g0 #f)) 1) #f)
     (#t (if #t #\㔋 #t))
     (#t (if #\U00085B2C #\U000E24F7 #\U000B5090))
     (2 1)
     (else
      (cond
       (#t #f)
       (1 #f)
       (#t 7)
       (#\騽 #t)
       (#t (sub1 #f))
       (#t #\U000A6836)
       (-4 #\U000D4111)
       (#f
        (cond
         ((char? -4) (if #f -2 0))
         ((- (cond (#\𣆕 5) (else #\ꓫ))) 4)
         ((cond (else #f)) #\U0010129D)
         (#f (if #t #t 4))
         (#t #t)
         ((if #f
            (cond
             (-5 (if #t #t #\ꦘ))
             (#t (if 1 3 #t))
             (#\슓 -7)
             ((cond (-1 #f) (#t 2) (else 2)) #t)
             ((if #\U000DA04B #t #t) #\鴭)
             (#\첐 (cond (9 #f) (#f #f) (#f 1) (#t #\U000E41D7) (else #\𢟾)))
             ((cond
               (#f #f)
               (#\ꄞ #t)
               (#t #t)
               (#f #\똜)
               (#f #t)
               (#f #f)
               (#t #t)
               (3 #\U000BFDAA)
               (#f #f)
               (#\鑖 #f)
               (#t #\ޥ)
               (else #f))
              #\U00044B87)
             ((cond
               (#f 2)
               (#t #f)
               (#f #t)
               (#\U000A95A1 #t)
               (#\U000BA42C -4)
               (#f #\U00018168)
               (else #t))
              #\Ὧ)
             ((abs -2) (cond (#t #t) (#f #f) (#t #\U000D8A16) (else -258)))
             (else (cond (else #t))))
            (if 2 #t #\U000A60A4))
          #t)
         (#t (cond (-9 #f) (else #\U000DBB07)))
         ((cond
           (#f (if (if 1 #t #t) (if #\U00031A5A #t #t) 4))
           (#\౧ #f)
           (#t (boolean? #\뺈))
           (#f (if -2 #t #f))
           ((cond
             (3 (abs #f))
             ((char->integer -4) (cond (4 #\U0002F197) (#t -1) (else 0)))
             ((cond (else #f)) #f)
             ((integer->char #t) #f)
             (#f (cond (#f #\U0002DE4B) (else -2)))
             (#f (abs #f))
             (#f (if #f 4 #\U0005D27B))
             (else 2))
            #\᳂)
           ((cond
             (4 2)
             (#f #\U00049C88)
             ((char? #f) -2)
             ((cond
               (#t #f)
               (#\U000781ED #f)
               (1 #t)
               (#f #f)
               (#t #t)
               (-2 #f)
               (#\쌐 #\씦)
               (#f #t)
               (#t #t)
               (else 3))
              1)
             (#f (cond (#\㘺 1) (#\圏 #f) (-1 #f) (else #f)))
             (#f 1)
             ((if #\U0008642D #t #t) #f)
             (#\习 #t)
             (#f (cond (#t #f) (#f -6) (else -17)))
             (#f (cond (#t #f) (else #t)))
             ((cond
               (#f #\뫑)
               (1 -1)
               (#\U00034677 -2)
               (#\U00049732 #f)
               (else #\U000D9274))
              (if #t #f 2))
             ((abs #f) (char? #\U0003F306))
             (#\U00080015
              (cond
               (#\U0004B7F2 -3)
               (#f #\U00099CDA)
               (#f #\ᔏ)
               (#f #\꺍)
               (else #f)))
             (else #f))
            #t)
           (#\U000F27EB #f)
           ((cond ((if #\殍 #f #t) (char->integer #\鼤)) (else #t))
            (cond (else #t)))
           (#f #f)
           (#t #f)
           (#\U000F6B78 (boolean? #\캓))
           (-1 #f)
           (#f #t)
           (#t #t)
           (#t #f)
           ((integer? #t) #t)
           (#\U001051DD 13)
           ((if #t (if #f #t #\U001083B2) 1) #f)
           ((- (if #f -2 2)) (zero? #f))
           (#t
            (if (cond (#f -2) (#f #t) (-2 #f) (else -5))
              #\U000DD565
              (cond (#\U000E7EA8 #t) (#t #f) (else #\ꎏ))))
           (#\뉕 (if #t #\U00076FFD 3))
           ((cond
             (#\枏 -4)
             ((if #\U000A167D #f #f) (integer->char #\U000E0A5C))
             (else #t))
            #\U000DDEFB)
           (else
            (cond
             (#t (cond (#f 2) (else #\U000654E1)))
             ((cond (#t #\颯) (1 #t) (#\滧 #\U00107D1A) (2 #\U000332B7) (else 2))
              (if #\𠧧 #f #t))
             (2 (- 5))
             ((if #t #f #\넅) (if #t #t #\u18FC))
             (#f (char? #f))
             (#\U00048822 (if -1 -1 #f))
             (1 #f)
             (-4 (integer->char 2))
             ((if #\U0006F98B #t #t) #f)
             ((cond (-4 #\훢) (#t 1) (-4 #t) (#t -3) (else -3)) 8)
             (else (cond (else 2))))))
          (cond (else (cond (else (cond (else #t)))))))
         ((- (if #f #t #t)) (sub1 #\U000DC51E))
         (else (integer->char #t))))
       (#f 130)
       (#t #f)
       (-8 #f)
       (2 #f)
       (#t 1)
       (else #\U000B98B7)))))
  #f)
