#lang racket
(cond
 ((cond
   (-4 (boolean? -10))
   ((let ((f0 #t))
      (cond
       (#f #t)
       (#t -1)
       (#t #\U0009ECDC)
       (f0 f0)
       (#t #f)
       (#\ઇ -1)
       (#\U000A9781 f0)
       (else f0)))
    (abs
     (cond
      (#f
       (cond
        ((if (- (if #t #t 2)) (sub1 (if #\㈻ -6 #f)) #\䰚) -2)
        ((if (char? 2) 4 (sub1 (cond (#\U000806B5 -2) (else #t))))
         (if (if (cond (else #t)) #f (integer? #f))
           #t
           (char? (zero? #\U000D5B77))))
        ((char? #t) #\U000FE3E2)
        (4 -16)
        ((if (if #t 4 (if 2 9 0)) #f #t) 1)
        (else #\U00074AEE)))
      (#f (if 4 (add1 (add1 (if #t #t #f))) #f))
      (#\⾨ #t)
      (#\㪕
       (cond
        (1
         (cond
          ((sub1 #t) #f)
          (#\U00103D05 #\ʵ)
          (#t -4)
          ((zero? 1) #\☪)
          (#\U0004BAAC
           (cond
            ((cond (#\U0002D1FA #\푛) (#t #t) (#f #f) (else #t)) #f)
            ((cond
              (9 2)
              (-5 1)
              (#f #t)
              (0 #t)
              (#\U000A8730 #t)
              (else #\U0002D365))
             #f)
            ((cond (#f #f) (#\鿇 #t) (#t #f) (else #t)) -3)
            ((sub1 #f) #\U000EB775)
            (#f #\州)
            (#f (if #f #f #t))
            (#\U000A988A (integer->char #t))
            (#\㔘 (cond (else 1)))
            ((cond (#f #f) (#f -4) (#\U000891F2 #f) (3 #\U000AE351) (else #f))
             #\걚)
            ((if #\U000C91BE #t -1) -1)
            ((cond (else #t)) (if -3 #\젨 #t))
            (#t (cond (4 #\⏞) (#f #f) (#t #\懠) (2 -1) (else #f)))
            (#\U0001A77E #\U00040CF7)
            (#f #\㓿)
            (#t (sub1 -1))
            ((cond
              (-2 #f)
              (#f #f)
              (#\U0006AD33 #\U000BB57C)
              (#t -3)
              (#t -1)
              (#t #\U00082269)
              (#\U00042C42 #t)
              (#\ॆ 0)
              (#\U00087F69 #t)
              (4 #f)
              (#t #t)
              (else #t))
             (zero? #t))
            (#\U00098F3D #\U0008B30A)
            (#\猒 3)
            (0 (if 0 -4 #\拿))
            ((abs #\⸄) (cond (#f #f) (1 #\∸) (#t 8) (else #f)))
            (else (cond (#\U000D3B93 #\ꌓ) (else #f)))))
          ((if (if 1 #\U000BD6C8 #f) #f #\躑) (abs #t))
          ((cond (else (if -2 -4 -8))) 3)
          (else 0)))
        (else -1)))
      (2 #f)
      ((boolean? #t) #\U000E9B9B)
      (#t (if (if #\U000D07DF (boolean? 33) #f) 3 17))
      (#t #t)
      ((add1 #\U00084FA0) #t)
      ((if (char->integer #t) (char? 65) -2) #f)
      (else 10))))
   (-1 #t)
   (#t #\U001062E7)
   (1 (if 3 #t #f))
   (else (if #\U00055CBA -2 -3)))
  #t)
 ((let ((k1 #\洓)) (cond (#f #t) (else k1))) #t)
 (#f -10)
 (#t #t)
 (#t (let ((p2 #t)) #\U000F34A4))
 (1 #t)
 ((if (let ((r1 #t)) r1)
    2
    (if (if (cond
             (#t -3)
             (#t #\U00058575)
             (else (cond ((if #t #t -1) (cond (else #t))) (else #t))))
          (zero? (integer? #\U000847DD))
          -1)
      (if #t #f #t)
      #\U0010B531))
  (let ((a1 #f)) (integer? (if #\u0B4A #f #\U000621E6))))
 ((cond
   (#\먼 (if -1 #\㟙 #t))
   (#f #\𨹂)
   (-2 #t)
   ((cond (else -2)) #\㈘)
   ((cond
     (#\U0006A9C0 #\氘)
     (#\U000B78EE #\U00084623)
     (#\U0010BAA1 3)
     (#f (if (char? #t) 2 (integer->char #t)))
     (else (if (if #t #\U000F1A5B #t) #\閿 #t)))
    (if 4
      (cond
       ((abs #f) (if #f #f #\㥂))
       ((if -2 #t #f) (- #t))
       (-2 #\푝)
       (#t #t)
       ((if #t #f -3) -4)
       ((cond (else #\萦)) (abs #t))
       ((char? -1)
        (cond
         (2 #\u200F)
         (#\U000841A7 -5)
         (#t -3)
         (#\U000938CC #\U000F6348)
         (-2 #\U00078A5D)
         (#\𠗳 6)
         (#f #f)
         (else #\U00076F06)))
       (132 (cond (-4 #f) (#\U00089F6E #t) (else #t)))
       (#\壼 (- 1))
       ((cond (#f #f) (#t #t) (else #\蕽)) #\蠷)
       (-4 (sub1 #t))
       ((boolean? #f) (if #f #\U0001E0C0 #t))
       ((sub1 #f) (if #t #t #f))
       (else #f))
      1))
   (else
    (if (cond
         ((if #t #t -1) #t)
         (2 (if #f #f #\矕))
         (#t #f)
         (#t #\U00109485)
         ((if #t #t #\㊤) (if #f #t #t))
         (-2 (cond (else #f)))
         (4 -7)
         (#\U00042DE1 #f)
         (#t (if -6 8 #\찎))
         (#f (cond (1 #t) (#t 1) (else #f)))
         ((if #\U000ED296 #t 0) (if 4 #\♪ -2))
         ((if #t #f #\U000C9501) 1)
         (else (cond (else #\蟻))))
      4
      #\ꃴ)))
  (let ((p1
         (let ((j0
                (cond
                 (#t #\ડ)
                 (#f #\䏗)
                 ((integer->char -4) -5)
                 (#f #\U000B679F)
                 (5 (sub1 #t))
                 (3 #t)
                 (#f (cond (#f #t) (else (- #f))))
                 (#f #\U0006E72B)
                 (#f -2)
                 (3
                  (if (cond
                       ((if #\U0009BBB7 #t -5) (if #f #t -8))
                       ((if #\U000DCA5D #\U000A967F -2) #t)
                       ((cond
                         (2 -1)
                         (#t #t)
                         (#\U0007B886 #f)
                         (-1 -4)
                         (#f #t)
                         (#f #\粡)
                         (#f #f)
                         (#t -9)
                         (-4 #f)
                         (#\諽 2)
                         (else #f))
                        #t)
                       ((cond (-8 #t) (else #t)) #f)
                       ((if #f #f -2) #t)
                       ((zero? 1) 2)
                       (#f
                        (cond
                         (1 #t)
                         (#f -1)
                         (#f #f)
                         (#t 7)
                         (#\謡 #\何)
                         (-1 -17)
                         (#t #\U000765F1)
                         (else 3)))
                       (#f -4)
                       ((cond (-1 #t) (1 #\凄) (-4 #f) (else #t))
                        (integer->char #\寲))
                       (#f (if 0 #f 1))
                       (#f -1)
                       (#\변 #f)
                       (else (if -2 -5 #\U0008828C)))
                    #t
                    #f))
                 (#f #t)
                 ((cond (else -10))
                  (cond
                   (#f #f)
                   ((if (integer? #\돫) #\U00038765 -2) (char? (- -1)))
                   ((cond
                     (#\U0010AE16 #\U00101B5D)
                     (-10
                      (cond
                       (#f #f)
                       (#\㮙 #t)
                       (#\ꓚ #f)
                       (4 #f)
                       (#t #f)
                       (1 #\們)
                       (#f -2)
                       (#f #f)
                       (#f #t)
                       (#t 8)
                       (#f #f)
                       (#f #f)
                       (#\兮 #t)
                       (#f #\U0008BD9F)
                       (-16 #\綎)
                       (else #t)))
                     (else #f))
                    (if (cond
                         (#\鎢 4)
                         (-5 #\錞)
                         (#\ዶ #f)
                         (#f #t)
                         (2 #t)
                         (else #t))
                      (if #f 2 #f)
                      (if #f #\U00082CD8 #f)))
                   ((boolean? (if #\鄩 2 -1)) 4)
                   ((if 3
                      (add1 0)
                      (cond
                       (#\밁 #\u16FE)
                       (#t #t)
                       (3 #\隖)
                       (#f #f)
                       (#f #\U00105FAA)
                       (#t 2)
                       (#f #t)
                       (-1 #t)
                       (1 #t)
                       (else #\U0002DA2A)))
                    #t)
                   (#f #t)
                   (#t #f)
                   ((sub1 (cond (-3 #\U0009C466) (else #t))) 2)
                   (#f (if (cond (0 #f) (else #t)) #f #t))
                   (#f #\U000391D7)
                   (else #\㹍)))
                 ((if #\措 (add1 (- #\U0010ECBC)) (add1 (integer->char #f))) 4)
                 (else -1))))
           (cond
            (#t #\ᝰ)
            (#f #t)
            (#t #\U00065031)
            (#t #t)
            (#\𧋥 #f)
            (#\悎 #\U0007017E)
            (#f j0)
            (#t #t)
            (else j0)))))
    #\䙴))
 ((add1 (let ((y1 (abs #\⽼))) #t)) #f)
 (256
  (if #f
    #t
    (cond
     (#\拁 #\U000F6E98)
     (else
      (if #\U0002D40F
        (if (cond
             ((cond
               (#\U00063B5A (cond (1 -2) (-3 7) (#t #\U000F0CA8) (else #\눷)))
               (0 #t)
               (#t 3)
               ((char->integer #t) #t)
               (#\U000C74D2 2)
               (#t #\刃)
               ((if 2 3 #t) #f)
               ((cond
                 (#f #t)
                 (#t #\熀)
                 (#t #f)
                 (#\㜮 #t)
                 (2 #f)
                 (#f #f)
                 (1 -4)
                 (-2 -1)
                 (else -4))
                (if -2 -2 1))
               (else (if #f #f #f)))
              (- #f))
             (#\죒 #t)
             ((cond
               (#\惏 #\팁)
               ((if #f #t #\U000331D4) (if #\邩 #t #\𠤗))
               (4 #\U000F0DAD)
               (-4 (if #f #f 1))
               (#t (cond (#f 1) (#f #\𦴔) (#\⟏ #t) (#\ܬ #t) (else 10)))
               (#t #f)
               ((if #f #f #\U00068F12) (cond (-64 #\씤) (else #f)))
               ((if -1 #t #\U00072B0E) #t)
               (-1 #f)
               (else #t))
              (cond (#f #f) (else #\楅)))
             (#\渢
              (if (cond (#f #\U000908CC) (#f #t) (#f 2) (else #\飭))
                #t
                (add1 1)))
             ((integer->char (if -5 #t 3))
              (cond
               (-5 (cond (else 3)))
               (#\U00071F3A #t)
               (-2
                (cond
                 (#f #\骬)
                 (#\轐 #\볺)
                 (#f #t)
                 (#f #\U000321CA)
                 (-1 #t)
                 (else #f)))
               ((cond (#t #\濹) (#\薺 #f) (#t #f) (else #t)) #\U00017307)
               (else (sub1 5))))
             (else #f))
          #\呞
          (cond (#f #t) (else #\U0002B858)))
        (cond (else 1)))))))
 (else (cond (else #\U0008397F))))
