#lang racket
(cond
 (#\u0D4F #\ꎷ)
 ((cond
   (#t #f)
   (#t #f)
   ((if (cond
         (#t
          (if #\U00062765
            0
            (cond (#t #\ὰ) (#\U00057E66 #t) (-16 #\U000BBEB9) (else 1))))
         (#\聘 #t)
         (#f #f)
         ((char->integer (if #f #f #f)) #t)
         (#\푻 #f)
         (-7 #\U000AE7F9)
         (else -1))
      #f
      #t)
    #t)
   (2 (sub1 (let ((b1 #f)) b1)))
   ((cond
     ((boolean? 3) #f)
     (#f 0)
     ((zero? (if (if #f 8 #t) (zero? #\U000AB0E1) (char? #t))) #\U0006C099)
     ((cond
       (#t #f)
       (2 #f)
       ((cond
         (-3 (cond (#t #t) (#\賒 -2) (else -2)))
         (#t (add1 #f))
         (5 (cond (else #t)))
         (#\U000E52F3 #f)
         ((if #\䶣 #\U0008BFFC -8) #\U000E7D31)
         (#f (cond (#f #\賩) (#\U00064DDF #t) (#t #t) (else #f)))
         (#t #\U000BC925)
         (else (integer? #\鹟)))
        #\刕)
       ((if #\U000E5384 (integer? #f) (add1 #\▕)) #t)
       ((if #\U00033CE2 (if #\݄ #f 2) (if #\華 -4 #f)) #\U000A5089)
       (1
        (if #\U000DA41E
          (cond (#f #f) (#\⌸ 1) (#\蕫 #\U000C00FE) (else #t))
          (cond (3 #f) (#t 8) (1 #f) (-2 2) (else -1))))
       (-7 #f)
       (1 -16)
       (else #f))
      (if #t (zero? (if 2 #f -1)) (char->integer (integer? -4))))
     (else
      (cond
       (#\썵 #f)
       (#\U0001AB2B (if (if #t #\U00096087 -1) #f (add1 #t)))
       (else (add1 (if #f #t #t))))))
    #t)
   ((sub1 #\U00072EBC) #\Ļ)
   ((cond
     ((cond (-3 #t) (else #f)) -2)
     (#\U000E0CCE (let ((g0 #t)) #t))
     ((if -4
        #\얃
        (if (cond
             (#\᮫ 2)
             ((add1 #t)
              (cond
               ((if #f #\뜽 #t) 5)
               ((if #\U00012BA3 #f -8) #\౾)
               (else (integer->char #f))))
             ((cond (else -1)) #f)
             (8
              (cond
               (#\U00061A22 #t)
               ((integer->char #f) #f)
               (#f (if #t #t #t))
               (else
                (cond
                 (2 #t)
                 (#f #t)
                 (#t #\U0010D07E)
                 (11 #\U000974FC)
                 (#f #f)
                 (#f #f)
                 (#t #t)
                 (else -8)))))
             (else (cond (else #f))))
          -3
          (integer->char #t)))
      (let ((q0 #t)) q0))
     ((char? #\U000F7B1B) #t)
     ((- #f) (if #t #t #f))
     ((cond (#\㚵 #f) (else -1)) #\䆾)
     (#\U000E7AA3 #\U00017515)
     (else #\Ș))
    2)
   (#\𪵔 #t)
   (else
    (cond
     (#\懘 (if #\U0006505A -4 #f))
     (#\ଶ (let ((g1 #f)) g1))
     (#\U000DFA21 #t)
     (else (let ((x0 #\𠒟)) #\㆚)))))
  -2)
 (#t
  (cond
   (#t 9)
   (#\숳 #t)
   ((cond ((if #f #f -3) #f) (else (boolean? #\U000BCCD2))) #t)
   ((if #\U000477A5 #\羒 #\ᨌ) #t)
   ((if (let ((w2 #f)) w2) #t (if (if #\U000E547F #f #t) #f 8))
    (cond
     ((char->integer 2) #f)
     (#\U000E4340 #t)
     ((-
       (if (if #t #\U0009B8EB #\U000F8471)
         #t
         (char->integer
          (cond
           (-2 #t)
           (-2 5)
           (#t #t)
           (3 #t)
           (#t #f)
           (#\U000B9660 1)
           (else #f)))))
      (if (cond (0 #\ꓺ) (else (if (add1 #t) #f 7))) #f 1))
     ((cond
       (#t #t)
       (#f -2)
       (#\U000C00DF -1)
       (#t #f)
       (#\U000325BC -5)
       (#\ℱ 2)
       (else -2))
      #f)
     (#t
      (if #f
        (cond
         ((if #f 3 #f) #f)
         ((if #t #\࿒ #t) (add1 #\U0002FCCD))
         (else
          (abs
           (cond
            (#\皭 (cond (else #\U000F6CBC)))
            (#t (char? #t))
            (3 #\鶙)
            (#\ዲ 2)
            (else (- #\癀))))))
        #\㢯))
     (else #t)))
   (#f
    (integer?
     (cond
      ((cond
        ((cond (else #t)) #\u1C9D)
        ((cond
          (#\U000A22D7 4)
          ((- #f) (if #t #f #t))
          (else (cond (#f #t) (3 #f) (2 #\뵔) (#\䢆 #t) (#t #f) (else #t))))
         (cond (#f #\㺴) (else #f)))
        ((- 0) 0)
        ((integer? 4) (if #f #f (if 1 #f #f)))
        (#f #f)
        (else (cond (else #f))))
       (cond
        (#f #\隽)
        (-21 #\䛺)
        ((- 0) #t)
        (#\Ạ 1)
        ((cond (else #f)) #\в)
        (else #f)))
      (#\U000B15C6
       (cond
        ((cond
          ((if 0 #\U00091776 #f) -3)
          (2
           (cond
            (#t #\U0002BDEA)
            (#t #t)
            (#t #t)
            (#f -1)
            (#t #\U0005BEAE)
            (#f #t)
            (#\U0006CD79 #f)
            (#t 16)
            (#t #t)
            (-5 #\U000498BF)
            (#t #\U000B8049)
            (else #\竓)))
          (#f (zero? #t))
          (#f (cond (#t #\U000E07C5) (1 -2) (#\ॖ #t) (else -3)))
          (#\ꅕ (cond (#f #f) (#\餔 -1) (8 5) (#t #\U0009FC00) (#t 1) (else #f)))
          (else #t))
         (if #t 1 #t))
        (else #\㡚)))
      (#f #\U000EF3ED)
      (2 #f)
      ((if #t (if #f (cond (4 -6) (-2 #t) (else -4)) #f) #\ຖ) #\U00076ABF)
      (#t -1)
      (#f (boolean? #f))
      (else (if (- (abs #f)) #t (zero? #f))))))
   (#t #\斠)
   ((if #t (let ((e1 -2)) e1) -6) #\냇)
   (#\U000180FD -6)
   ((if #f
      #t
      (cond
       (#\荏 #t)
       (#\U00067A7C
        (cond
         (-1 -16)
         (else
          (cond
           ((zero? 4) (if #\㴅 #\U000B8974 (- #\U0003FC30)))
           ((cond
             ((zero? #t) (if #t 1 #f))
             ((cond (-1 1) (-8 #t) (#t #\퀺) (-2 #f) (#\𐅡 #f) (else #t))
              (cond (#t #t) (#\U000C6C8F #t) (else #\u1ADC)))
             ((if #t #t #f) (if 1 -2 #t))
             (#f (cond (-2 #\U00014632) (else #\U000FC4ED)))
             ((cond
               (#f 9)
               (#t -1)
               (#\⾙ #t)
               (#\ᘱ #f)
               (#t #t)
               (#f #\U000B1758)
               (#f 4)
               (#\௷ -5)
               (3 #\💁)
               (-6 #f)
               (3 #f)
               (#\齃 #\U0004862D)
               (#\U000B7D28 #f)
               (#t -5)
               (#t #f)
               (1 #t)
               (#f #\U0004E279)
               (else #f))
              (if #f 66 #\Ⴙ))
             (#f (sub1 #f))
             (#f #f)
             ((sub1 #f) (if #f #\ꆊ #f))
             (#\䏼 (add1 #\u0B0D))
             (#f #t)
             (else (abs #t)))
            (if (cond (else #t)) #\U000C61F0 -2))
           (#t (if (cond (#t #\맂) (else #\U0003A952)) #f (cond (else 2))))
           ((if #t #\༨ (if 4 #f 3))
            (cond
             ((cond (#f -2) (else #\U000C5ADC)) #\U00090299)
             (#f 1)
             ((cond (#t #t) (else #t)) #f)
             (#t #\钟)
             (else (cond (#\U000B921B #t) (else #f)))))
           (#f #\U0007DA67)
           (#\U000174D2 (zero? #f))
           (#f #f)
           (#\堩 #t)
           (#f #t)
           (else (if -2 -17 (if 3 3 3)))))))
       (#\摪 #\U000EDB63)
       (#t
        (cond
         ((if #f 1 #t) #\U000135AC)
         (#\U000B940B #f)
         ((cond
           ((- #\젮) #f)
           (#f #t)
           ((cond
             ((abs #\쵥) (if #t #\୭ #f))
             ((cond (-2 #f) (else #t)) (char->integer #\U0003A94E))
             (#t 5)
             ((char? #f) (if #t 1 #\U000993E2))
             (else 4))
            (cond (#t (cond (-1 -2) (else #t))) (else #t)))
           ((abs -6) #f)
           ((if (if #\눧 1 #t) -2 #\U0008EFB6) #f)
           ((abs #f) #f)
           ((integer->char (add1 0)) 4)
           ((cond
             (#f (if 4 4 #f))
             ((char? -130) (integer->char -2))
             ((cond
               (#\❘ #\誶)
               (#\玏 #f)
               (#t #f)
               (#f #f)
               (#f 1)
               (#f #f)
               (#t 4)
               (else -2))
              #t)
             ((cond (4 #t) (else 4)) (if #f #f #t))
             (-8 #\U0008955D)
             (#t #f)
             (3 #f)
             (#\Ѣ #t)
             (else 9))
            (- #\u1CB0))
           ((if #t (if #f #f #t) (if #t #\볱 #f)) 2)
           (#f (sub1 (zero? #f)))
           ((char? #\ᖐ) 1)
           ((cond (else 7)) (integer? 2))
           (#t 0)
           (#t
            (cond
             ((add1 #f) (if #\U0006CE9C 3 #t))
             (#t #\揰)
             (#\U000E2CDF (if -5 #t 5))
             (#\鉼 (if #\ᮎ #t #t))
             (#f (- #\嵩))
             (-1 -64)
             ((cond (else #f)) #\緟)
             (else (abs #t))))
           ((char? 4) #t)
           (else -3))
          #t)
         ((integer? #\U00053015) #f)
         (else #t)))
       (#\㩬 #t)
       (3 -2)
       (#\蒺 #f)
       (#t #\U001080F1)
       (else 1)))
    (boolean? #t))
   (#t (zero? #\ଋ))
   ((if -32 (if 3 #\튉 #f) (boolean? 17))
    (cond
     ((let ((j0 #f)) #f) (if #\U0005F41C #t #\ꕔ))
     ((cond (else #\U000DB1E5))
      (add1
       (if (cond
            (#\졬 #\ꤸ)
            (-5 (sub1 #f))
            ((cond
              (#\U000E2134 -3)
              (1 #t)
              (#\팊 0)
              (2 #t)
              (#f #t)
              (#\易 #f)
              (#t #\䠎)
              (#t #\멦)
              (#\齳 #f)
              (#f #\U00099EA8)
              (#t #t)
              (#\㎞ #\⍻)
              (1 #t)
              (#t #\U)
              (#\U000CA009 #\U0007AA57)
              (else -4))
             (if #t #f #\繣))
            (#t (cond (#f #f) (else #t)))
            (else
             (cond
              (-2 18)
              (#\⫓ 1)
              (-1 #f)
              (#\U00014CC7 #f)
              (#\U000B1F63 #t)
              (#t #\獂)
              (5 #t)
              (3 #\鷀)
              (1 -17)
              (-1 #t)
              (else 5))))
         (cond
          ((- #t) (if #f #t #\㹉))
          (-2 (boolean? #\U0006DA00))
          (#f #f)
          (#\U0010C277 #t)
          (#t -1)
          (#t (cond (else #t)))
          (else #\U00057D15))
         #\U00092584)))
     (-8
      (cond
       (2 #f)
       ((cond
         (1 #\栰)
         (-16 #\U00092C8F)
         (else
          (if (if (cond (-5 #t) (#f 3) (-4 #t) (else #\U000729D1))
                (cond
                 (3 #t)
                 (-4 #t)
                 (#t #t)
                 (#f #t)
                 (#t #t)
                 (#f #f)
                 (-17 #\U00078735)
                 (else #t))
                #t)
            #t
            #\獯)))
        #t)
       (#t #f)
       ((abs #t) 3)
       (#t #f)
       (#\U000A19C3 5)
       (#t #\U000A4459)
       (#\꒬ #t)
       (#\U000C3BDC #t)
       (#\U0010186B #t)
       (#\U0005F0C6 #t)
       ((if (cond (else (- #f)))
          #f
          (if #t
            (cond (4 #t) (#\騙 #f) (else (zero? #\㟑)))
            (abs (integer? #f))))
        #t)
       (#t #\U000E1681)
       (#t #t)
       (#t (integer? (if (if (boolean? -2) #t #t) #f 0)))
       ((cond
         (5
          (cond
           ((if (if #f -2 #f) -2 (char? #\쑀)) (cond (else #f)))
           ((integer->char (if 3 #f #\బ)) (if (char->integer -16) #f (sub1 5)))
           ((cond
             (35 (cond (#t 16) (-1 #f) (#t #t) (else -2)))
             (#t 1)
             (#t -3)
             (#f -1)
             (#\U0002DD00 (sub1 #\技))
             (#\탴 #t)
             ((cond (#f #f) (else #f)) (if #t #f #f))
             (else #f))
            #\噒)
           (else
            (abs
             (cond
              (-1 #\պ)
              (#\鉁 #t)
              (#\U000B7F04 #\U001006AE)
              (-1 #\綎)
              (#f 4)
              (#f -4)
              (2 #t)
              (#t #f)
              (0 #\U00035767)
              (else 9))))))
         (else #f))
        #f)
       (#t -3)
       (#t #t)
       (#\儵 #\U00072818)
       (else -4)))
     ((- #f) (cond (else -11)))
     (else (boolean? (cond (#f #f) (1 16) (0 #t) (else #f))))))
   (else (if 2 (let ((t1 #\烾)) 1) -1))))
 (#f 4)
 (#\錜 #t)
 (4 #f)
 ((let ((n0 #t)) #\騇)
  (cond
   (#t
    (cond
     ((cond
       (#\U000D118B (if -3 #t #f))
       ((char? #t) #f)
       ((if 11 #\U0010FE61 #f) (integer? #\U0008E896))
       (else
        (cond
         (#t #f)
         (#\츇 #f)
         (-5 #\U0008747C)
         (#\U00067570 #f)
         (-1 #\햑)
         (-4 #f)
         (#t #f)
         (#\㥯 #t)
         (else #\U00015191))))
      #f)
     (else 3)))
   (-2 -2)
   ((char->integer #f)
    (if (cond
         (#\U0009920F -16)
         ((if #f 1 -6) (add1 #f))
         (#t
          (cond
           (#f #\U000F8055)
           (#\U000F7BF2 #f)
           (#t #\U000DEA03)
           (#f #t)
           (#f #t)
           (#t #f)
           (else #\⭓)))
         (else #\鯛))
      -9
      (char->integer #f)))
   ((if (if #f
          (if -2 0 3)
          (cond
           (-3 #f)
           (#t #\多)
           (#t #\U00070C5E)
           (#t #f)
           (#t #\斺)
           (#t #t)
           (#\酩 #f)
           (else #f)))
      #\U0009DF47
      #f)
    #\⧔)
   (else (if (if #\ᝥ #\ӗ #f) #t (if #\U000E5B6C (integer? #f) #\U000474AF)))))
 (else
  (cond
   (1 -5)
   ((let ((h1 #\U00048519)) (let ((n0 #t)) #t)) #\邖)
   ((cond
     ((cond (#t -3) (#t #f) (#\壙 #\U00059B41) (#\曈 #f) (else #t)) #t)
     ((cond (else #\U0010A109)) (if #f #\U0005FD3C #t))
     ((cond
       (-1 -4)
       (3 #\䟹)
       (#t #\뿛)
       (2 #\U0009B338)
       (-7 #t)
       ((if (integer->char #f)
          (if (cond
               ((cond (-128 #f) (else #f)) #t)
               ((char? -2) (add1 #t))
               (#t -1)
               ((char->integer -3) -2)
               ((sub1 #f) (zero? #\U000BE95F))
               ((integer->char #\텅) #t)
               (else
                (cond
                 (1 #\U00050875)
                 (#f #t)
                 (-5 -15)
                 (#\U0009164A 2)
                 (#f #t)
                 (else 3))))
            2
            (boolean? (cond (else #f))))
          #f)
        #\雜)
       (5 #\u0E7E)
       (#f -8)
       (#t #\#)
       (else 3))
      (if #t #\U00089B3B #t))
     ((if #\喕 #f -1) (cond (1 #f) (#f 0) (#\幋 #\ᢿ) (#t #f) (8 #t) (else 19)))
     (else (let ((c0 #t)) #t)))
    -3)
   (#t (cond (else (add1 #f))))
   ((cond
     (1
      (cond
       (3 #t)
       (-3 #t)
       (-1 #\U0001B25B)
       ((cond
         (#t
          (cond
           ((add1 (sub1 #f)) #t)
           (#f (char->integer (if #\꒻ 1 #\홠)))
           (#\礜 #t)
           (else #t)))
         ((cond
           (-1 -1)
           ((cond
             ((if #t -4 #\噉) (char? #t))
             (#\䧼 (if #t #\U00059C98 -2))
             (#\藃 -2)
             (#t 4)
             ((cond
               (1 -1)
               (2 #\U000D5A0F)
               (-32 #f)
               (#f #\땅)
               (#\U0009D7C6 3)
               (#t #\풑)
               (#\U000EE939 #t)
               (#f #t)
               (4 #f)
               (else 1))
              #f)
             (1 (if #f #t #t))
             ((if #t -2 #f) (boolean? #t))
             (#t 16)
             (#\䄻 #t)
             ((sub1 -3) #\ꢞ)
             ((cond (else -2)) #f)
             (#f #f)
             ((cond
               (#f #\䴯)
               (#\U000EF3B8 #f)
               (#t 1)
               (#t #f)
               (#f #\㜩)
               (#t #\ⶶ)
               (#f -2)
               (-2 -3)
               (0 #\旳)
               (#f 4)
               (#f #t)
               (#f #t)
               (#t #\呒)
               (else #\妝))
              (cond (#t #\ý) (65 #\uAB63) (1 #\uE598) (#t -2) (else #t)))
             (else (boolean? #\U000FD0A8)))
            (integer->char (char->integer #t)))
           (#\U000D415E (if 0 #\U00050FC0 #\돣))
           (#t #t)
           (0 3)
           (#t (add1 (cond (else #\U0006A3AD))))
           (else #f))
          #\˼)
         (#\U00034A5E #\U0007A9D7)
         (#t (if #\᪩ (integer->char 5) (integer->char #t)))
         (#t #\㞾)
         ((if #\U00108DFE (abs #\쇭) #t)
          (if #f
            (cond (#\U00053580 -6) (else -5))
            (if (cond (-1 #t) (else #t)) #f (if #\U000951A7 -1 #f))))
         ((if #\U001074EB
            (cond (#t (cond (#f #f) (else #f))) (else (cond (else #t))))
            #t)
          #\U000C34E0)
         (else #f))
        #f)
       (else
        (cond
         ((cond
           (#t #t)
           (#f (- 6))
           (#\U000ADED2 (if (if #f -4 4) #t (if #f 4 -2)))
           ((if #\U000E809E (char? -2) #\뼿) -5)
           ((if 3 #t 1) (cond (else #f)))
           (#t #f)
           ((char->integer #f) -2)
           ((if (- #\空) #\U0006C878 (boolean? #\웋)) #\췴)
           (-2 -5)
           (#t #\썒)
           (else (sub1 2)))
          #t)
         (#t (if #f #f #t))
         (else #\⌜)))))
     (else #\ퟗ))
    (if (if 1 #\Ⱨ #\U00075B2A) #\稧 (if -8 #\癅 #t)))
   (#f (if -2 (let ((r0 #f)) r0) #f))
   ((let ((r1 #f)) 1)
    (cond
     ((cond (#t #\⇣) (else #f)) #f)
     ((if #\떤 #\摦 #t)
      (if #f
        (boolean?
         (if (if (cond
                  (#f #\U00030944)
                  (#\U0001F99F #t)
                  (#f #\棟)
                  (#f #f)
                  (4 4)
                  (3 -1)
                  (#t 33)
                  (#\U0009468A 1)
                  (5 #f)
                  (-2 #f)
                  (-4 #f)
                  (#f #\ᖾ)
                  (#t #f)
                  (-2 #t)
                  (#f -2)
                  (0 5)
                  (0 #\৲)
                  (#f #f)
                  (#t #t)
                  (else #t))
               #\U0008A79F
               (if #t #f #t))
           (add1
            (cond
             (#f #t)
             (#\ӷ #f)
             (#f #\ᣢ)
             (2 #\U0004E2CE)
             (#\弶 #\火)
             (#t #f)
             (else 1)))
           5))
        #f))
     ((abs
       (cond
        ((cond (else #f)) #f)
        (#f 3)
        ((if (cond
              (#\ꁇ #\U00067CF0)
              ((cond (#f -1) (#\U0003D76E 3) (#\u088E #t) (else #\U0007099D))
               (if #\珹 #\U000BAFF5 #\牅))
              (else #t))
           #\U00084B1F
           #t)
         (cond
          (#t #f)
          (1 (zero? 3))
          ((- #f) #f)
          (#f
           (cond
            (else
             (cond
              (#t #t)
              (#\彧 #f)
              (#\U000D6BCD #t)
              (#f #f)
              (#f #f)
              (#t 7)
              (#\U0006CDE4 -1)
              (#t -5)
              (0 5)
              (-2 #f)
              (#t #\U000DD342)
              (1 -4)
              (#\Ը #f)
              (else #t)))))
          (#t #f)
          ((integer->char #\숮) (integer? -2))
          (#f #\諑)
          ((cond
            (#t #\U00050840)
            ((integer->char #\욫) #t)
            ((cond (3 #f) (2 #\耂) (#f 1) (-2 #\뢫) (else #f)) (boolean? 5))
            (#f #f)
            ((boolean? #t) #f)
            (-2 (if -3 -1 #\u0530))
            (else #\U000C5286))
           (- (if #f #f #\횅)))
          (-2 -5)
          (#t #\U00089C32)
          ((abs (boolean? #\U000D7895)) #f)
          (#\蟓 #\轠)
          ((if #f #t 2) #f)
          ((integer->char #t) #\U000A1CD4)
          (#\꺰 (zero? -2))
          (#f #f)
          ((if #\娄 (cond (#t #t) (20 1) (else 1)) #t) #f)
          ((char->integer #f) #t)
          ((cond
            ((sub1 #t) #\㡫)
            ((- #f) #f)
            (#\U0003ECE6
             (cond
              (#f #t)
              (#t #\U000E49E9)
              (#f #\U0003E96B)
              (#f #f)
              (#t #t)
              (#\𢅨 #\U000C5A05)
              (#t #\쬡)
              (-3 #\U000C16CB)
              (#t #f)
              (#f #t)
              (-11 #t)
              (#\U000F89DA 5)
              (#t #\蹼)
              (else #\𠵞)))
            (else #f))
           (cond
            (#t #t)
            (else
             (cond
              (-2 #\U000888F9)
              (0 #t)
              (#f #t)
              (#f #t)
              (2 #t)
              (#f #\䥞)
              (-10 #\U00079FB7)
              (#t #\鹈)
              (else -2)))))
          ((cond
            (else
             (cond
              (#t -2)
              (#f #\月)
              (#f #\U000C14FF)
              (1 #t)
              (-3 #t)
              (#t 2)
              (#f #f)
              (4 #t)
              (1 #t)
              (3 2)
              (#\㪂 #f)
              (#\u0D53 #t)
              (else -2))))
           (cond ((if 8 32 #f) #f) (else (if #t #t #t))))
          (-3 5)
          ((cond
            (#f #\U00053FCB)
            ((if #t #f 1) #t)
            ((char->integer #f) #f)
            (#f -2)
            (else #f))
           (add1 -1))
          (else #t)))
        (else 7)))
      #f)
     ((cond (#t #t) (else 5)) #f)
     (#f -1)
     (#\U00047DF6 -3)
     (else #f)))
   ((cond
     (35 #f)
     (#f #t)
     (#f (let ((p0 1)) p0))
     (#t (integer? #f))
     ((abs -32) (if 2 -1 #t))
     (else 32))
    (cond ((let ((n0 #t)) #t) #\u2428) (else -1)))
   (68
    (cond
     (#t (abs #t))
     (#f (let ((x0 #f)) #t))
     (#f #f)
     ((cond
       (#\奐 #t)
       (#\U0008D98C #t)
       (#\U000E6881 -1)
       (#f #f)
       (else #\U000E2B28))
      #f)
     ((cond
       (#\䇍 -2)
       (#f #\U000640CB)
       (#\掠 #\U0002FF4F)
       (#\𓊧 #f)
       (#f #t)
       (#t #\U000EDFCC)
       (else #t))
      (cond (else 3)))
     (else #f)))
   ((integer->char (char->integer #\杄))
    (cond
     (#\U000141F0 #f)
     ((abs #t) (if #t -4 #\U000AD0AB))
     ((zero? 1) (if -1 4 (char? (if #t #t -4))))
     (3
      (cond
       (4 -3)
       (#f 8)
       ((if (if (sub1 #\啛) (cond (else #f)) #t) (cond (else #t)) #f) #f)
       (#\赑
        (cond
         ((cond
           ((if #t #\U000EEE9C #\U00072671) -1)
           ((cond (else #t)) (if #f #f #\U0010D709))
           (5 (cond (#\ආ 4) (else -2)))
           (-5 #t)
           (else (cond (else -3))))
          (cond
           (else
            (cond
             (#\⚽ 2)
             (#\挚 #f)
             (#f #f)
             (#f 0)
             (#\U000D21FF #f)
             (#f -3)
             (#t #t)
             (#f 4)
             (else -5)))))
         ((cond (#t (cond (else #f))) (#t (boolean? #\U00014869)) (else #\㭖))
          #f)
         (else (cond (else #t)))))
       ((char? (cond (else #t))) 5)
       ((if #\鷥
          (if (char->integer #f)
            (cond (16 #f) (#f #f) (#f #t) (else #\롦))
            (sub1 #f))
          (cond
           ((add1 #f) #\U0007B77E)
           ((abs -2) #\U00109120)
           ((integer->char #\U000B43DB) (sub1 #f))
           ((cond (#f #f) (#\U000FEF28 #\墥) (else -1))
            (cond
             (#t #f)
             (2 #f)
             (3 #f)
             (#f -3)
             (4 #t)
             (0 -3)
             (#t -1)
             (else #t)))
           ((cond
             (-2 #f)
             (#\⮎ #f)
             (5 #\U000F27A9)
             (#\U000BA164 #t)
             (#\岏 1)
             (else #\U00104CAE))
            (if #t 1 #t))
           (#f (if #\U001007BA #f #\U000F82CF))
           (1 (cond (#\U000117A6 #\U000C44C1) (else #\U000C55F8)))
           (else (if #t #t #\畺))))
        (if #t
          #f
          (if (cond
               (#f -4)
               (1 #\䋙)
               (#t #f)
               (#f #\U00037900)
               (#\U000D3F2D #\鰂)
               (#t 4)
               (#t #\భ)
               (1 #\跦)
               (else #f))
            3
            #f)))
       (#t -3)
       (else #t)))
     (#t #\U00072614)
     (5 (if -2 #t #t))
     (#t (let ((t2 -1)) #t))
     (else (let ((h0 #f)) h0))))
   (else #\U000E125C))))
