#lang racket
(cond
 ((cond
   (#\U000D7857 #f)
   (#\U0005229D #\脂)
   ((integer->char #t) #t)
   ((cond
     (#t #\U000E3A53)
     (#\놾 (let ((n2 #t)) #f))
     ((cond
       (#t #t)
       (#f #f)
       (-1 #t)
       (#f #f)
       (-5 #f)
       ((if #\摇
          (if #\剨
            (cond
             (#f #\U000EF066)
             (#t (if #f #t #t))
             ((if #f #f #\U0007A394) (cond (#t #\尽) (else #f)))
             (else -4))
            (char->integer (if 4 -2 #t)))
          #f)
        #t)
       (#t 2)
       (#f #\U0007D965)
       (#f #\U0005A59F)
       (-1 2)
       (#f #f)
       (#t -3)
       (#f
        (if (cond
             ((cond (#f #f) (#t 0) (else (if 2 #f #f)))
              (integer->char (cond (#f 5) (#t #f) (#t #\U0007AAE1) (else #f))))
             (#f #\U000BD710)
             (else
              (cond
               ((cond
                 (3 #t)
                 (#t #\鬘)
                 (#f -4)
                 (#f #\㯃)
                 (#f #t)
                 (#\U000EA05A #t)
                 (#t #\U0006A343)
                 (#f #\U0009F78F)
                 (-1 #\U00067396)
                 (#f #f)
                 (#t -5)
                 (else #\U000E99B4))
                (cond (#f #\ླ) (0 #\ⱗ) (#t 4) (else #f)))
               (#f -8)
               (else -4))))
          #t
          #f))
       ((if (zero? #f) #f #t) #\ႊ)
       (#t #f)
       (else #f))
      (integer? 2))
     (else (integer? 64)))
    (let ((z0 #t)) (cond (else 0))))
   ((let ((s1 #\U000458A9)) (zero? #f)) #t)
   ((cond
     ((if #t #t #\U000C66F9) #f)
     (#t #t)
     (#f
      (if #\U00059116
        (cond
         ((cond
           (#\U000CDDB0
            (cond
             (-4 128)
             (#\桅 #\憤)
             (#t #f)
             (#f -2)
             (#t #f)
             (#f #f)
             (#t #\䦦)
             (-1 #f)
             (#\U0007D628 -4)
             (#t #\U000412EE)
             (#\壃 5)
             (#t #\U0006B96E)
             (else #t)))
           (#t 0)
           (#t (char->integer #\U000316E9))
           (33 -3)
           (else -16))
          17)
         (1 -3)
         ((abs
           (cond
            (#f -4)
            (#\U000C1DE7 -2)
            (-2 #t)
            (#t -4)
            (#\雊 4)
            (#t #\U0006877B)
            (#\噈 9)
            (#\U000314DE -8)
            (1 -4)
            (#f #\U00079C42)
            (#t #f)
            (#\U0005961E #f)
            (#t #\U00063324)
            (0 #\痡)
            (else #f)))
          #t)
         (5 (boolean? (cond (#\U000ED830 -8) (#f #t) (else #\U000AF330))))
         ((if (- -1)
            #t
            (cond
             (#f -5)
             (#t -4)
             (#\⇭ #f)
             (#t #\霰)
             (3 #t)
             (3 #t)
             (-1 -6)
             (#t -1)
             (#t #f)
             (#t #t)
             (#f 5)
             (-8 4)
             (else #\U00058CAD)))
          #\U0005526A)
         (#t (add1 #t))
         ((boolean? (sub1 #\痊)) (if 4 -4 #f))
         (else
          (cond
           (-3 #\U000AD054)
           ((char->integer #\ܰ) #\⽖)
           ((cond
             (#\᯲ #f)
             (#t #f)
             (#t #\U0002D4DA)
             (#t -4)
             (9 #t)
             (2 #f)
             (#\⏫ 1)
             (#\뷶 #\U0009C26D)
             (else -7))
            #f)
           ((cond (else 2)) (if -3 8 #t))
           ((char->integer #\ᒶ) (integer? #t))
           (#f #t)
           (else #\Ⲡ))))
        #t))
     (#\쿰 (if #t (sub1 #f) 1))
     ((abs 4) (if #\U00054AFC #f #t))
     (else (sub1 2)))
    #t)
   (else -2))
  (cond (else (if (boolean? 3) 3 (char? #f)))))
 (-1 -3)
 ((char? (sub1 #t)) #t)
 ((if (cond (#t (char->integer #f)) (else (let ((b0 #\U00046EEE)) #t))) #f #t)
  #t)
 (#t (if #\룆 -17 (sub1 (let ((z2 #t)) #f))))
 ((let ((q2 #f)) (sub1 q2)) (let ((a2 #\軡)) a2))
 ((boolean? (zero? #f))
  (char?
   (if -2
     (add1 (if (if #\뿴 #f (- (cond (#t #t) (2 -2) (else -1)))) #\襗 #f))
     #t)))
 ((boolean? (abs #t)) #\U00033F28)
 ((let ((u0 #\U0007C613))
    (cond
     ((cond (#\U0004D8D5 #\伃) (#f #f) (u0 1) (4 u0) (#f u0) (else 32)) u0)
     ((let ((h1 #f)) -1) #t)
     (else #t)))
  (cond
   ((cond (else (if #f -5 #\㳳))) #\䫼)
   ((if (zero? -2) #\U000E9D50 (abs -1)) -1)
   (else #\삽)))
 (#t #t)
 ((if (if (let ((s1 -2)) s1) #\휮 #t) #\U000B5762 -4) #\鼦)
 (else (if (let ((p0 -3)) #\㈾) (abs (if #t #f #f)) -65)))
